Repository softeerbootcamp-2nd/H5-MyCarMaster, pull requests merged in 2023-08, with the labels that each got.

#50 [Setting] 개발환경 세팅
  .github/BE_ACTIONS/dev-ci.yml
  .gitignore
  BE-MyCarMaster/build.gradle
Labels: ✨ be, 🛠 setting

#53 [Feature] 재사용 컴포넌트 생성 - 1
  FE-MyCarMaster/src/App.css
  FE-MyCarMaster/src/App.tsx
  FE-MyCarMaster/src/assets/icons/AngleDown.svg
  FE-MyCarMaster/src/assets/icons/AngleUp.svg
  FE-MyCarMaster/src/assets/icons/ArrowLeft.svg
  FE-MyCarMaster/src/assets/icons/ArrowRight.svg
  FE-MyCarMaster/src/assets/icons/ArrowUp.svg
  FE-MyCarMaster/src/assets/icons/CircleBasicPlus.svg
  FE-MyCarMaster/src/assets/icons/CircleBasicXMark.svg
  FE-MyCarMaster/src/assets/icons/CircleCheck.svg
  FE-MyCarMaster/src/assets/icons/CircleOriginalPlus.svg
  FE-MyCarMaster/src/assets/icons/CircleOriginalXMark.svg
  FE-MyCarMaster/src/assets/icons/Square.svg
  FE-MyCarMaster/src/assets/icons/SquareCheck.svg
  FE-MyCarMaster/src/assets/icons/XMark.svg
  FE-MyCarMaster/src/components/common/Button/Button.tsx
  FE-MyCarMaster/src/components/common/Button/TextButton.tsx
  FE-MyCarMaster/src/components/common/CategoryList/CategoryItem.tsx
  FE-MyCarMaster/src/components/common/CategoryList/CategoryList.tsx
  FE-MyCarMaster/src/components/common/ColorBox/OuterColorBox.tsx
  FE-MyCarMaster/src/pages/Estimation.tsx
  FE-MyCarMaster/src/styles/Color.ts
Labels: 🙇🏿‍♂️ fe, 🚀 feature

#54 [Setting] 프로젝트 세팅
  iOS-MyCarMaster/.gitignore
  iOS-MyCarMaster/MyCarMaster/.swiftlint.auto.yml
  iOS-MyCarMaster/MyCarMaster/.swiftlint.yml
  iOS-MyCarMaster/MyCarMaster/MyCarMaster.xcodeproj/project.pbxproj
  iOS-MyCarMaster/MyCarMaster/MyCarMaster.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iOS-MyCarMaster/MyCarMaster/MyCarMaster.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/App/AppDelegate.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/App/SceneDelegate.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Resources/Assets.xcassets/Contents.json
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Resources/Base.lproj/LaunchScreen.storyboard
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Resources/Info.plist
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/ViewController.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMasterTests/MyCarMasterTests.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMasterUITests/MyCarMasterUITests.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMasterUITests/MyCarMasterUITestsLaunchTests.swift
Labels: 🍎 ios, 🛠 setting

#56 [Setting] PR template update
  .github/pull_request_template.md
Labels: ✨ be, 🛠 setting

#58 [Feature] 재사용 컴포넌트 생성 - 2
  FE-MyCarMaster/src/App.tsx
  FE-MyCarMaster/src/assets/images/InnerColor.png
  FE-MyCarMaster/src/components/Footer/Footer.tsx
  FE-MyCarMaster/src/components/Header/Header.tsx
  FE-MyCarMaster/src/components/common/ColorBox/InnerColorBox.tsx
  FE-MyCarMaster/src/components/common/OptionBox/OptionBox.tsx
  FE-MyCarMaster/src/index.css
  FE-MyCarMaster/src/pages/Estimation.tsx
  FE-MyCarMaster/src/styles/Color.ts
  FE-MyCarMaster/src/styles/GlobalStyle.ts
Labels: 🙇🏿‍♂️ fe, 🚀 feature

#61 [Setting] code lint 설정
  .github/workflows/be-dev-ci.yml
  BE-MyCarMaster/.editorconfig
  BE-MyCarMaster/build.gradle
  BE-MyCarMaster/config/checkstyle/naver-checkstyle-rules.xml
  BE-MyCarMaster/config/checkstyle/naver-checkstyle-suppressions.xml
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/BeMyCarMasterApplication.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/HealthController.java
  BE-MyCarMaster/src/test/java/softeer/bemycarmaster/BeMyCarMasterApplicationTests.java
Labels: ✨ be, 🛠 setting

#66 [Setting] appspec 추가
  .github/workflows/be-release-cd.yml
  BE-MyCarMaster/appspec.yml
Labels: ✨ be, 🛠 setting

#67 [Release] appspec 추가
  .github/workflows/be-release-cd.yml
  BE-MyCarMaster/appspec.yml
Labels: ✨ be, 🔖 release

#68 [Chore] cd workflow의 작업 경로 수정
  .github/workflows/be-release-cd.yml
Labels: ✨ be, 🍻 chore

#69 [Release] cd workflow의 작업 경로 수정
  .github/workflows/be-release-cd.yml
Labels: ✨ be

#70 [Refactor] 견적서 만들기 레이아웃 구성
  FE-MyCarMaster/src/App.tsx
  FE-MyCarMaster/src/components/Footer/Footer.tsx
  FE-MyCarMaster/src/components/Header/Header.tsx
  FE-MyCarMaster/src/components/Main/MainView.tsx
  FE-MyCarMaster/src/components/Main/MainWrapper.tsx
  FE-MyCarMaster/src/components/Main/view/ColorContent.tsx
  FE-MyCarMaster/src/components/Main/view/DetailModelContent.tsx
  FE-MyCarMaster/src/components/Main/view/OptionContent.tsx
  FE-MyCarMaster/src/components/Main/view/TrimContent.tsx
  FE-MyCarMaster/src/index.css
  FE-MyCarMaster/src/main.tsx
Labels: 🙇🏿‍♂️ fe, ♻️ refactor

#75 [Release] Dockerfile에서 Env값 관리
  .github/workflows/be-release-cd.yml
  BE-MyCarMaster/Dockerfile
  BE-MyCarMaster/src/main/resources/application-domain.yml
Labels: ✨ be, 🛠 setting

#76 [Design] Trim View 구성
  FE-MyCarMaster/src/assets/images/exclusive.png
  FE-MyCarMaster/src/assets/images/leblanc.png
  FE-MyCarMaster/src/components/Main/view/TrimContent.tsx
Labels: 🙇🏿‍♂️ fe, 🎨 design

#77 [Feature] 재사용 컴포넌트 생성 - 2
  FE-MyCarMaster/src/components/Main/MainView.tsx
  FE-MyCarMaster/src/components/common/CategoryList/CategoryItem.tsx
  FE-MyCarMaster/src/components/common/NavigationList/EstimatedPrice.tsx
  FE-MyCarMaster/src/components/common/NavigationList/NavigationItem.tsx
  FE-MyCarMaster/src/components/common/NavigationList/NavigationList.tsx
Labels: 🙇🏿‍♂️ fe, 🚀 feature

#80 [Setting] CD를 위한 appspec 내용 추가
  BE-MyCarMaster/appspec.yml
Labels: ✨ be, 🛠 setting

#81 [Release] appspec 내용 추가후 배포
  BE-MyCarMaster/appspec.yml
Labels: ✨ be, 🔖 release

#83 [Feature] 홈 화면 레이아웃 구성
  FE-MyCarMaster/src/assets/images/dark_logo.svg
  FE-MyCarMaster/src/assets/images/logo.svg
  FE-MyCarMaster/src/assets/images/white_logo.svg
  FE-MyCarMaster/src/components/Header/Header.tsx
  FE-MyCarMaster/src/components/common/NavigationList/NavigationItem.tsx
  FE-MyCarMaster/src/components/common/NavigationList/NavigationList.tsx
  FE-MyCarMaster/src/pages/Estimation.tsx
  FE-MyCarMaster/src/pages/Home.tsx
Labels: 🙇🏿‍♂️ fe, 🚀 feature

#84 [Feature] 홈 화면 레이아웃 구성
  FE-MyCarMaster/src/App.tsx
  FE-MyCarMaster/src/components/common/Button/Button.tsx
  FE-MyCarMaster/src/main.tsx
  FE-MyCarMaster/src/pages/Estimation.tsx
  FE-MyCarMaster/src/pages/Home.tsx
  FE-MyCarMaster/src/pages/Quotation.tsx
Labels: 🙇🏿‍♂️ fe, 🚀 feature

#85 [Design] 홈 화면 레이아웃 구성
  FE-MyCarMaster/src/pages/Home.tsx
Labels: 🙇🏿‍♂️ fe, 🎨 design

#86 [Release] 홈 화면 프론트엔드 배포
  FE-MyCarMaster/src/App.tsx
  FE-MyCarMaster/src/assets/images/dark_logo.svg
  FE-MyCarMaster/src/assets/images/logo.svg
  FE-MyCarMaster/src/assets/images/white_logo.svg
  FE-MyCarMaster/src/components/Header/Header.tsx
  FE-MyCarMaster/src/components/common/Button/Button.tsx
  FE-MyCarMaster/src/components/common/NavigationList/NavigationItem.tsx
  FE-MyCarMaster/src/components/common/NavigationList/NavigationList.tsx
  FE-MyCarMaster/src/main.tsx
  FE-MyCarMaster/src/pages/Estimation.tsx
  FE-MyCarMaster/src/pages/Home.tsx
  FE-MyCarMaster/src/pages/Quotation.tsx
Labels: 🙇🏿‍♂️ fe, 🔖 release

#89 [Design] 홈 화면 비디오 디자인 수정
  FE-MyCarMaster/src/components/Footer/Footer.tsx
  FE-MyCarMaster/src/components/Header/Header.tsx
  FE-MyCarMaster/src/components/Main/MainView.tsx
  FE-MyCarMaster/src/components/Main/MainWrapper.tsx
  FE-MyCarMaster/src/components/Main/view/ColorContent.tsx
  FE-MyCarMaster/src/components/Main/view/DetailModelContent.tsx
  FE-MyCarMaster/src/components/Main/view/OptionContent.tsx
  FE-MyCarMaster/src/components/Main/view/TrimContent.tsx
  FE-MyCarMaster/src/components/common/ColorBox/InnerColorBox.tsx
  FE-MyCarMaster/src/components/common/NavigationList/EstimatedPrice.tsx
  FE-MyCarMaster/src/components/common/NavigationList/NavigationItem.tsx
  FE-MyCarMaster/src/components/common/NavigationList/NavigationList.tsx
  FE-MyCarMaster/src/components/common/OptionBox/OptionBox.tsx
  FE-MyCarMaster/src/pages/Estimation.tsx
  FE-MyCarMaster/src/pages/Home.tsx
  FE-MyCarMaster/src/pages/Quotation.tsx
  FE-MyCarMaster/vercel.json
Labels: 🙇🏿‍♂️ fe, 🔖 release

#90 [Setting] 프론트엔드 Vercel 배포
  FE-MyCarMaster/src/components/Footer/Footer.tsx
Labels: 🙇🏿‍♂️ fe, 🛠 setting

#93 [Feat] 엔진 목록 조회 swagger 문서 작성
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/engine/controller/EngineController.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/engine/dto/request/GetEnginesRequest.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/engine/dto/response/Engine.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/engine/dto/response/GetEnginesResponse.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/engine/usecase/GetEnginesUseCase.java
Labels: ✨ be, 🚀 feature

#94 [Feat] 구동방식 목록 조회 swagger 문서 작성
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/wheeldrive/controller/WheelDriveController.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/wheeldrive/dto/request/GetWheelDrivesRequest.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/wheeldrive/dto/response/GetWheelDrivesResponse.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/wheeldrive/dto/response/WheelDrive.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/wheeldrive/usecase/GetWheelDrivesUseCase.java
Labels: ✨ be, 🚀 feature

#95 [Feat] 바디타입 목록 조회 swagger 문서 작성
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/bodytype/controller/BodyTypeController.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/bodytype/dto/request/GetBodyTypesRequest.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/bodytype/dto/response/BodyType.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/bodytype/dto/response/GetBodyTypesResponse.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/bodytype/usecase/GetBodyTypesUseCase.java
Labels: ✨ be, 🚀 feature

#102 [Setting] SwiftLint disabled rule 추가
  iOS-MyCarMaster/MyCarMaster/.swiftlint.yml
Labels: 🍎 ios, 🛠 setting

#96 [Feature] 외장 색상 목록 조회 swagger 문서 작성
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/color/controller/ColorController.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/color/dto/request/GetExteriorColorsRequest.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/color/dto/response/ExteriorColor.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/color/dto/response/GetExteriorColorsResponse.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/color/dto/response/InteriorColor.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/color/usecase/GetExteriorColorsUseCase.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/color/usecase/GetInteriorColorsUseCase.java
Labels: ✨ be, 🚀 feature

#103 [Setting] 프론트 Vercel 배포 테스트
  FE-MyCarMaster/README.md
  FE-MyCarMaster/src/pages/Home.tsx
Labels: 🙇🏿‍♂️ fe, 🛠 setting

#97 [Feature] 추가 옵션 목록 조회 swagger 문서 작성
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/option/controller/OptionController.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/option/dto/request/GetOptionsRequest.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/option/dto/response/GetOptionsResponse.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/option/dto/response/Option.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/option/dto/response/OptionEnum.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/option/dto/response/SubOption.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/option/usecase/GetOptionsUseCase.java
Labels: ✨ be, 🚀 feature

#105 [Release] Swagger 작성 및 CORS 설정
  .gitmodules
  BE-MyCarMaster/build.gradle
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/bodytype/controller/BodyTypeController.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/bodytype/dto/request/GetBodyTypesRequest.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/bodytype/dto/response/BodyType.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/bodytype/dto/response/GetBodyTypesResponse.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/bodytype/usecase/GetBodyTypesUseCase.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/color/controller/ColorController.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/color/dto/request/GetExteriorColorsRequest.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/color/dto/request/GetInteriorColorsRequest.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/color/dto/response/ExteriorColor.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/color/dto/response/GetExteriorColorsResponse.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/color/dto/response/GetInteriorColorsResponse.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/color/dto/response/InteriorColor.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/color/usecase/GetExteriorColorsUseCase.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/color/usecase/GetInteriorColorsUseCase.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/engine/controller/EngineController.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/engine/dto/request/GetEnginesRequest.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/engine/dto/response/Engine.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/engine/dto/response/GetEnginesResponse.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/engine/usecase/GetEnginesUseCase.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/model/controller/ModelController.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/model/dto/response/GetModelsResponse.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/model/dto/response/Model.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/model/usecase/GetModelsUseCase.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/option/controller/OptionController.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/option/dto/request/GetOptionsRequest.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/option/dto/response/GetOptionsResponse.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/option/dto/response/Option.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/option/dto/response/OptionEnum.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/option/dto/response/SubOption.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/option/usecase/GetOptionsUseCase.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/trim/controller/TrimController.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/trim/dto/request/GetTrimsRequest.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/trim/dto/response/GetTrimsResponse.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/trim/dto/response/Trim.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/trim/usecase/GetTrimsUseCase.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/wheeldrive/controller/WheelDriveController.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/wheeldrive/dto/request/GetWheelDrivesRequest.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/wheeldrive/dto/response/GetWheelDrivesResponse.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/wheeldrive/dto/response/WheelDrive.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/wheeldrive/usecase/GetWheelDrivesUseCase.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/global/annotation/UseCase.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/global/config/cors/CorsConfig.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/global/config/swagger/SwaggerConfig.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/global/response/Response.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/global/response/ResponseStatus.java
  BE-MyCarMaster/src/main/resources/application-api.yml
Labels: ✨ be, 🔖 release

#106 [Feature] Footer 레이아웃을 구성한다.
  FE-MyCarMaster/src/components/Footer/Footer.tsx
  FE-MyCarMaster/src/components/Header/Header.tsx
  FE-MyCarMaster/src/components/common/Button/Button.tsx
  FE-MyCarMaster/src/pages/Home.tsx
Labels: 🙇🏿‍♂️ fe, 🚀 feature

#108 [Feature] Context Provider 구성
  FE-MyCarMaster/src/App.tsx
  FE-MyCarMaster/src/components/Header/Header.tsx
  FE-MyCarMaster/src/contexts/CarPaintContext.tsx
  FE-MyCarMaster/src/contexts/DetailContext.tsx
  FE-MyCarMaster/src/contexts/ModelContext.tsx
  FE-MyCarMaster/src/contexts/OptionContext.tsx
  FE-MyCarMaster/src/contexts/QuotationContext.tsx
  FE-MyCarMaster/src/contexts/TrimContext.tsx
Labels: 🙇🏿‍♂️ fe, 🚀 feature

#110 [Feature] 배포유형 변경에 따른 Script 추가
  .github/workflows/be-release-cd.yml
  BE-MyCarMaster/appspec.yml
  BE-MyCarMaster/scripts/appspec.yml
  BE-MyCarMaster/scripts/create-directory.sh
  BE-MyCarMaster/scripts/pull-and-run-container.sh
  BE-MyCarMaster/scripts/remove-container.sh
Labels: ✨ be, 🛠 setting

#111 [Release] 배포유형 변경
  .github/workflows/be-release-cd.yml
  BE-MyCarMaster/appspec.yml
  BE-MyCarMaster/scripts/appspec.yml
  BE-MyCarMaster/scripts/create-directory.sh
  BE-MyCarMaster/scripts/pull-and-run-container.sh
  BE-MyCarMaster/scripts/remove-container.sh
Labels: ✨ be, 🔖 release

#112 [Chore] appspec의 script location 수정
  BE-MyCarMaster/scripts/appspec.yml
Labels: ✨ be, 🛠 setting

#113 [Release] 배포 스크립트의 location 수정
  BE-MyCarMaster/scripts/appspec.yml
Labels: ✨ be, 🔖 release

#114 [Feature] 외장 색상 예외 처리 로직 추가
  BE-MyCarMaster/build.gradle
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/color/controller/ColorController.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/color/dto/request/GetInteriorColorsRequest.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/color/exterior/controller/ExteriorColorController.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/color/exterior/dto/request/GetExteriorColorsRequest.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/color/exterior/dto/response/ExteriorColorDto.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/color/exterior/dto/response/GetExteriorColorsResponse.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/color/exterior/usecase/GetExteriorColorsUseCase.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/color/interior/controller/InteriorColorController.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/color/interior/dto/request/GetInteriorColorsRequest.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/color/interior/dto/response/GetInteriorColorsResponse.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/color/interior/dto/response/InteriorColor.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/color/interior/usecase/GetInteriorColorsUseCase.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/color/usecase/GetExteriorColorsUseCase.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/global/exception/GlobalExceptionHandler.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/global/exception/MyCarMasterException.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/global/response/Response.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/global/response/ResponseStatus.java
  BE-MyCarMaster/src/main/resources/application-api.yml
  BE-MyCarMaster/src/test/java/softeer/bemycarmaster/api/domain/color/exterior/controller/ExteriorColorControllerTest.java
Labels: ✨ be, 🚀 feature

#115 [Feature] 내장 색상 예외 처리 로직 추가
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/color/interior/controller/InteriorColorController.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/color/interior/dto/request/GetInteriorColorsRequest.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/color/interior/dto/response/GetInteriorColorsResponse.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/color/interior/dto/response/InteriorColorDto.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/color/interior/usecase/GetInteriorColorsUseCase.java
  BE-MyCarMaster/src/test/java/softeer/bemycarmaster/api/domain/color/exterior/controller/ExteriorColorControllerTest.java
  BE-MyCarMaster/src/test/java/softeer/bemycarmaster/api/domain/color/interior/controller/InteriorColorControllerTest.java
Labels: ✨ be, 🚀 feature

#116 [Feature] 바디타입 목록 조회 예외 처리 로직 추가
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/bodytype/controller/BodyTypeController.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/bodytype/dto/request/GetBodyTypesRequest.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/bodytype/dto/response/BodyTypeDto.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/bodytype/dto/response/GetBodyTypesResponse.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/bodytype/usecase/GetBodyTypesUseCase.java
  BE-MyCarMaster/src/test/java/softeer/bemycarmaster/api/domain/bodytype/controller/BodyTypeControllerTest.java
Labels: ✨ be, 🚀 feature

#117 [Feature] 모델 목록 조회 구현
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/model/domain/Model.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/model/dto/response/GetModelsResponse.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/model/dto/response/Model.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/model/dto/response/ModelDto.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/model/infrastructure/ModelEntity.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/model/infrastructure/ModelJpaAdaptor.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/model/infrastructure/ModelJpaRepository.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/model/usecase/GetModelsUseCase.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/model/usecase/port/ModelPort.java
  BE-MyCarMaster/src/test/java/softeer/bemycarmaster/api/domain/model/controller/ModelControllerTest.java
  BE-MyCarMaster/src/test/java/softeer/bemycarmaster/api/domain/model/usecase/GetModelsUseCaseTest.java
Labels: ✨ be, 🚀 feature

#109 [Feature] 견적 요약 네비게이션 생성
  FE-MyCarMaster/src/components/Footer/Footer.tsx
  FE-MyCarMaster/src/components/Main/MainView.tsx
  FE-MyCarMaster/src/components/Main/MainWrapper.tsx
  FE-MyCarMaster/src/contexts/QuotationContext.tsx
Labels: 🙇🏿‍♂️ fe, 🚀 feature

#121 [Feature] 엔진, 구동방식, 바디타입 뷰를 구성한다.
  FE-MyCarMaster/src/assets/images/2WD.png
  FE-MyCarMaster/src/assets/images/BodyType_7.png
  FE-MyCarMaster/src/assets/images/diesel.png
  FE-MyCarMaster/src/components/Main/view/DetailModelContent.tsx
  FE-MyCarMaster/src/components/Main/view/DetailModelView/BodyTypeView.tsx
  FE-MyCarMaster/src/components/Main/view/DetailModelView/DetailModelWrapper.tsx
  FE-MyCarMaster/src/components/Main/view/DetailModelView/EngineView.tsx
  FE-MyCarMaster/src/components/Main/view/DetailModelView/WheelDriveView.tsx
Labels: 🙇🏿‍♂️ fe, 🚀 feature

#118 [Feature] 구동방식 목록 조회 예외 처리 로직 추가
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/bodytype/controller/BodyTypeController.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/wheeldrive/controller/WheelDriveController.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/wheeldrive/dto/request/GetWheelDrivesRequest.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/wheeldrive/dto/response/GetWheelDrivesResponse.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/wheeldrive/dto/response/WheelDriveDto.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/wheeldrive/usecase/GetWheelDrivesUseCase.java
  BE-MyCarMaster/src/test/java/softeer/bemycarmaster/api/domain/wheeldrive/controller/WheelDriveControllerTest.java
Labels: ✨ be, 🚀 feature

#119 [Feature] 엔진 목록 조회 예외 처리 로직 추가
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/engine/controller/EngineController.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/engine/dto/request/GetEnginesRequest.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/engine/dto/response/EngineDto.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/engine/dto/response/GetEnginesResponse.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/engine/usecase/GetEnginesUseCase.java
  BE-MyCarMaster/src/test/java/softeer/bemycarmaster/api/domain/engine/controller/EngineControllerTest.java
Labels: ✨ be, 🚀 feature

#120 [Feature] 트림 목록 조회 예외 처리 로직 추가
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/trim/controller/TrimController.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/trim/dto/request/GetTrimsRequest.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/trim/dto/response/GetTrimsResponse.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/trim/dto/response/TrimDto.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/trim/usecase/GetTrimsUseCase.java
  BE-MyCarMaster/src/test/java/softeer/bemycarmaster/api/domain/trim/controller/TrimControllerTest.java
Labels: ✨ be, 🚀 feature

#122 [Feature] 엔진 뷰를 구성하고 최고출력, 최대토크, 복합 연비 프로그래스 바를 구성한다.
  FE-MyCarMaster/src/components/Main/view/DetailModelView/EngineView.tsx
  FE-MyCarMaster/src/components/common/CategoryList/CategoryItem.tsx
  FE-MyCarMaster/src/components/common/CategoryList/CategoryList.tsx
  FE-MyCarMaster/src/components/common/Graph/GraphItem.tsx
  FE-MyCarMaster/src/components/common/Graph/GraphList.tsx
  FE-MyCarMaster/src/components/common/Graph/ProgressBar.tsx
  FE-MyCarMaster/src/constants/Graph.constants.ts
Labels: 🙇🏿‍♂️ fe, 🚀 feature

#125 [Feature] 견적 요약 네비게이션 생성
  FE-MyCarMaster/src/components/Footer/Footer.tsx
  FE-MyCarMaster/src/components/Main/MainWrapper.tsx
  FE-MyCarMaster/src/components/common/NavigationList/EstimatedPrice.tsx
  FE-MyCarMaster/src/components/common/NavigationList/NavigationItem.tsx
  FE-MyCarMaster/src/components/common/NavigationList/NavigationList.tsx
  FE-MyCarMaster/src/contexts/QuotationContext.tsx
  FE-MyCarMaster/src/types/quotation.types.ts
  FE-MyCarMaster/src/utils/indexNameSwitching.ts
Labels: 🙇🏿‍♂️ fe, 🚀 feature

#123 [Feature] 엔진에 변경 따라 선택불가능해지는 옵션 목록 조회 swagger 문서 작성
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/engine/controller/EngineController.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/engine/dto/request/GetUnselectableOptionsByEngineRequest.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/engine/dto/response/GetUnselectableOptionsByEngineResponse.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/engine/dto/response/UnselectableOptionDto.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/engine/usecase/GetEnginesUseCase.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/engine/usecase/GetUnselectableOptionsByEngineUseCase.java
  BE-MyCarMaster/src/test/java/softeer/bemycarmaster/api/domain/engine/controller/EngineControllerTest.java
Labels: ✨ be, 🚀 feature

#128 [Feature] 하단 뷰 구성 및 컴포넌트 디자인
  FE-MyCarMaster/src/components/Footer/Footer.tsx
  FE-MyCarMaster/src/components/Footer/SelectListWrapper.tsx
  FE-MyCarMaster/src/components/Footer/view/ColorSelect.tsx
  FE-MyCarMaster/src/components/Footer/view/DetailModelSelect.tsx
  FE-MyCarMaster/src/components/Footer/view/OptionSelect.tsx
  FE-MyCarMaster/src/components/Footer/view/TrimSelect.tsx
  FE-MyCarMaster/src/components/common/ColorBox/InnerColorBox.tsx
  FE-MyCarMaster/src/components/common/ColorBox/OuterColorBox.tsx
  FE-MyCarMaster/src/components/common/OptionBox/OptionBox.tsx
  FE-MyCarMaster/src/contexts/CarPaintContext.tsx
  FE-MyCarMaster/src/contexts/DetailContext.tsx
  FE-MyCarMaster/src/contexts/OptionContext.tsx
  FE-MyCarMaster/src/contexts/TrimContext.tsx
Labels: 🙇🏿‍♂️ fe, 🚀 feature

#127 [Feature] 엔진에 변경 따라 선택불가능해지는 옵션 목록 조회 예외 처리 로직 추가
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/engine/controller/EngineController.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/engine/dto/request/GetUnselectableOptionsByEngineRequest.java
  BE-MyCarMaster/src/main/java/softeer/bemycarmaster/api/domain/engine/dto/response/UnselectableOptionDto.java
  BE-MyCarMaster/src/test/java/softeer/bemycarmaster/api/domain/engine/controller/EngineControllerTest.java
Labels: ✨ be, 🚀 feature

#133 [Feature] 외장 색상 목록 조회 구현
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/color_exterior/controller/ExteriorColorController.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/color_exterior/dto/request/GetExteriorColorsRequest.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/color_exterior/dto/response/ExteriorColorDto.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/color_exterior/dto/response/GetExteriorColorsResponse.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/color_exterior/usecase/GetExteriorColorsUseCase.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/color_exterior/usecase/port/ExteriorColorPort.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/domain/color_exterior/ExteriorColor.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/domain/model/Model.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/domain/trim/Trim.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/annotation/Domain.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/color_exterior/adaptor/ExteriorColorJpaAdaptor.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/color_exterior/entity/ExteriorColorEntity.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/color_exterior/entity/TrimExteriorColorEntity.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/color_exterior/repository/TrimExteriorColorJpaRepository.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/model/adaptor/ModelJpaAdaptor.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/model/entity/ModelEntity.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/model/repository/ModelJpaRepository.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/trim/adaptor/TrimJpaAdaptor.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/trim/entity/TrimEntity.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/trim/repository/TrimJpaRepository.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/model/ModelJpaRepository.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/color_exterior/controller/ExteriorColorControllerTest.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/color_exterior/usecase/GetExteriorColorsUseCaseTest.java
Labels: ✨ be, 🚀 feature

#136 [Feature] 하단 뷰 구성 및 컴포넌트 디자인
  FE-MyCarMaster/src/components/Footer/view/ColorSelect.tsx
  FE-MyCarMaster/src/components/Footer/view/DetailModelSelect.tsx
  FE-MyCarMaster/src/components/Footer/view/OptionSelect.tsx
  FE-MyCarMaster/src/components/Footer/view/TrimSelect.tsx
  FE-MyCarMaster/src/components/Main/view/ColorContent.tsx
  FE-MyCarMaster/src/components/common/Button/Button.tsx
  FE-MyCarMaster/src/components/common/ColorBox/InnerColorBox.tsx
  FE-MyCarMaster/src/components/common/ColorBox/OuterColorBox.tsx
  FE-MyCarMaster/src/components/common/NavigationList/NavigationItem.tsx
  FE-MyCarMaster/src/components/common/OptionBox/OptionBox.tsx
  FE-MyCarMaster/src/contexts/CarPaintContext.tsx
  FE-MyCarMaster/src/contexts/DetailContext.tsx
  FE-MyCarMaster/src/contexts/OptionContext.tsx
  FE-MyCarMaster/src/contexts/QuotationContext.tsx
  FE-MyCarMaster/src/contexts/TrimContext.tsx
  FE-MyCarMaster/src/styles/Theme.ts
  FE-MyCarMaster/src/types/options.types.ts
  FE-MyCarMaster/src/types/quotation.types.ts
Labels: 🙇🏿‍♂️ fe, 🚀 feature, 🎨 design

#137 [Feature] Network Layer Base
  iOS-MyCarMaster/MCMNetwork/.gitignore
  iOS-MyCarMaster/MCMNetwork/MCMNetwork.xcodeproj/project.pbxproj
  iOS-MyCarMaster/MCMNetwork/MCMNetwork.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iOS-MyCarMaster/MCMNetwork/MCMNetwork.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS-MyCarMaster/MCMNetwork/MCMNetwork.xcodeproj/xcshareddata/xcschemes/MCMNetwork.xcscheme
  iOS-MyCarMaster/MCMNetwork/MCMNetwork/Examples/GithubSearch/GithubSearchRepository.swift
  iOS-MyCarMaster/MCMNetwork/MCMNetwork/Examples/GithubSearch/GithubTarget.swift
  iOS-MyCarMaster/MCMNetwork/MCMNetwork/Examples/GithubSearch/ResponseModel.swift
  iOS-MyCarMaster/MCMNetwork/MCMNetwork/MCMNetwork.h
  iOS-MyCarMaster/MCMNetwork/MCMNetwork/README.md
  iOS-MyCarMaster/MCMNetwork/MCMNetwork/Resources/Dependency.swift
  iOS-MyCarMaster/MCMNetwork/MCMNetwork/Sources/DecodedDataTaskPublisher.swift
  iOS-MyCarMaster/MCMNetwork/MCMNetwork/Sources/DownloadTaskPublisher.swift
  iOS-MyCarMaster/MCMNetwork/MCMNetwork/Sources/Endpoint.swift
  iOS-MyCarMaster/MCMNetwork/MCMNetwork/Sources/HTTPMethod.swift
  iOS-MyCarMaster/MCMNetwork/MCMNetwork/Sources/NetworkError.swift
  iOS-MyCarMaster/MCMNetwork/MCMNetwork/Sources/NetworkProvider.swift
  iOS-MyCarMaster/MCMNetwork/MCMNetwork/Sources/TargetType.swift
  iOS-MyCarMaster/MCMNetwork/MCMNetwork/Sources/Task.swift
  iOS-MyCarMaster/MCMResource/MCMResource.xcodeproj/project.pbxproj
  iOS-MyCarMaster/MCMResource/MCMResource.xcodeproj/xcshareddata/xcschemes/MCMResource.xcscheme
  iOS-MyCarMaster/MCMResource/MCMResource/Resource.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster.xcodeproj/project.pbxproj
  iOS-MyCarMaster/MyCarMaster/MyCarMaster.xcodeproj/xcshareddata/xcschemes/MyCarMaster.xcscheme
  iOS-MyCarMaster/MyCarMaster/MyCarMaster.xcodeproj/xcshareddata/xcschemes/MyCarMasterTests.xcscheme
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Onboarding/OnboardingViewController.swift
Labels: 🍎 ios, 🚀 feature, sprint[⼆]

#138 [Feature] 바디타입 목록 조회 구현
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/body_type/controller/BodyTypeController.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/body_type/dto/request/GetBodyTypesRequest.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/body_type/dto/response/BodyTypeDto.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/body_type/dto/response/GetBodyTypesResponse.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/body_type/usecase/GetBodyTypesUseCase.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/body_type/usecase/port/BodyTypePort.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/domain/body_type/BodyType.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/body_type/BodyTypeEntity.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/body_type/BodyTypeJpaAdaptor.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/body_type/BodyTypeJpaRepository.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/trim/adaptor/TrimJpaAdaptor.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/trim/repository/TrimJpaRepository.java
  BE-MyCarMaster/src/main/resources/application-api.yml
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/body_type/controller/BodyTypeControllerTest.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/body_type/usecase/GetBodyTypesUseCaseTest.java
Labels: ✨ be, 🚀 feature

#139 [Feature] 트림 뷰 구성
  FE-MyCarMaster/src/assets/images/Calligraphy.png
  FE-MyCarMaster/src/assets/images/Prestige.png
  FE-MyCarMaster/src/assets/images/exclusive.png
  FE-MyCarMaster/src/assets/images/leblanc.png
  FE-MyCarMaster/src/components/Main/view/TrimContent.tsx
  FE-MyCarMaster/src/contexts/TrimContext.tsx
Labels: 🙇🏿‍♂️ fe, 🚀 feature

#140 [Feature] 엔진 목록 조회 구현
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/engine/dto/response/EngineDto.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/engine/dto/response/GetEnginesResponse.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/engine/usecase/GetEnginesUseCase.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/engine/usecase/port/EnginePort.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/domain/body_type/BodyType.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/domain/engine/Engine.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/body_type/adaptor/BodyTypeJpaAdaptor.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/body_type/entity/BodyTypeEntity.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/body_type/repository/BodyTypeJpaRepository.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/engine/adpator/EngineJpaAdaptor.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/engine/entity/EngineEntity.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/engine/entity/TrimEngineEntity.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/engine/repository/TrimEngineJpaRepository.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/engine/usecase/GetEnginesUseCaseTest.java
Labels: ✨ be, 🚀 feature

#145 [Feature] 세부모델 뷰 구성
  FE-MyCarMaster/src/assets/images/4WD.png
  FE-MyCarMaster/src/assets/images/BodyType_7.png
  FE-MyCarMaster/src/assets/images/BodyType_8.png
  FE-MyCarMaster/src/assets/images/Gasoline.png
  FE-MyCarMaster/src/components/Main/view/DetailModelView/BodyTypeView.tsx
  FE-MyCarMaster/src/components/Main/view/DetailModelView/EngineView.tsx
  FE-MyCarMaster/src/components/Main/view/DetailModelView/WheelDriveView.tsx
  FE-MyCarMaster/src/components/common/Graph/GraphItem.tsx
  FE-MyCarMaster/src/components/common/Graph/GraphList.tsx
  FE-MyCarMaster/src/contexts/DetailContext.tsx
Labels: 🙇🏿‍♂️ fe, 🚀 feature

#147 [Feature] 구동방식 목록 조회 구현
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/wheeldrive/controller/WheelDriveController.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/wheeldrive/dto/request/GetWheelDrivesRequest.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/wheeldrive/dto/response/GetWheelDrivesResponse.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/wheeldrive/dto/response/WheelDriveDto.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/wheeldrive/usecase/GetWheelDrivesUseCase.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/wheeldrive/usecase/port/WheelDrivePort.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/domain/wheel_dirve/WheelDrive.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/wheel_drive/adaptor/WheelDriveJpaAdaptor.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/wheel_drive/entity/TrimWheelDriveEntity.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/wheel_drive/entity/UnselectableEngineWheelDriveEntity.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/wheel_drive/entity/WheelDriveEntity.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/wheel_drive/repository/TrimWheelDriveJpaRepository.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/wheel_drive/repository/UnselectableEngineWheelDriveJpaRepository.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/wheeldrive/controller/WheelDriveControllerTest.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/wheeldrive/usecase/GetWheelDrivesUseCaseTest.java
Labels: ✨ be, 🚀 feature

#148 [Feature] 옵션 Footer Item에 따른 메인 컨텐츠 변경
  FE-MyCarMaster/src/assets/icons/CirclePagination.svg
  FE-MyCarMaster/src/components/Footer/view/OptionSelect.tsx
  FE-MyCarMaster/src/components/Main/view/OptionContent.tsx
  FE-MyCarMaster/src/components/common/ColorBox/InnerColorBox.tsx
  FE-MyCarMaster/src/components/common/ColorBox/OuterColorBox.tsx
  FE-MyCarMaster/src/components/common/OptionBox/OptionBox.tsx
  FE-MyCarMaster/src/components/common/OptionDescription/OptionDescription.tsx
  FE-MyCarMaster/src/contexts/OptionContext.tsx
  FE-MyCarMaster/src/types/options.types.ts
Labels: 🙇🏿‍♂️ fe, 🚀 feature

#154 [ Design] 컴포넌트 디자인 및 스타일 포맷
  FE-MyCarMaster/src/components/Footer/Footer.tsx
  FE-MyCarMaster/src/components/common/ColorBox/InnerColorBox.tsx
  FE-MyCarMaster/src/components/common/ColorBox/OuterColorBox.tsx
  FE-MyCarMaster/src/components/common/ColorBox/style.ts
  FE-MyCarMaster/src/components/common/Graph/GraphItem.tsx
  FE-MyCarMaster/src/components/common/Graph/ProgressBar.tsx
  FE-MyCarMaster/src/components/common/NavigationList/EstimatedPrice.tsx
  FE-MyCarMaster/src/components/common/NavigationList/NavigationItem.tsx
  FE-MyCarMaster/src/components/common/OptionBox/OptionBox.tsx
  FE-MyCarMaster/src/styles/Color.ts
  FE-MyCarMaster/src/styles/Theme.ts
Labels: 🙇🏿‍♂️ fe, 🎨 design

#152 [Setting] 테이블명 설정
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/color_exterior/entity/TrimExteriorColorEntity.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/color_interior/entity/TrimInteriorColorEntity.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/color_interior/entity/UnselectableExteriorInteriorEntity.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/engine/entity/TrimEngineEntity.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/wheel_drive/entity/TrimWheelDriveEntity.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/wheel_drive/entity/UnselectableEngineWheelDriveEntity.java
Labels: ✨ be, 🛠 setting

#151 [Feature] 엔진 변경에 따라 선택불가능해지는 옵션 목록 조회 구현
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/engine/dto/response/GetUnselectableOptionsByEngineResponse.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/engine/dto/response/UnselectableOptionDto.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/engine/usecase/GetUnselectableOptionsByEngineUseCase.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/engine/usecase/GetUnselectableOptionsByEngineUseCaseTest.java
Labels: ✨ be, 🚀 feature

#156 [Design] 버튼 컴포넌트 디자인
  FE-MyCarMaster/public/images/interior/interiorColor.png
  FE-MyCarMaster/src/components/common/Button/Button.tsx
  FE-MyCarMaster/src/components/common/Button/TextButton.tsx
  FE-MyCarMaster/src/components/common/Button/style.ts
  FE-MyCarMaster/src/components/common/ColorBox/InnerColorBox.tsx
  FE-MyCarMaster/src/components/common/ColorBox/style.ts
  FE-MyCarMaster/src/components/common/OptionBox/OptionBox.tsx
  FE-MyCarMaster/src/contexts/CarPaintContext.tsx
  FE-MyCarMaster/src/styles/Theme.ts
Labels: 🙇🏿‍♂️ fe, 🎨 design

#158 [Setting] ddl-auto 설정
  BE-MyCarMaster/src/main/resources/application-domain.yml
Labels: ✨ be, 🛠 setting

#159 [Fix] 엔진 목록 조회시 toque값이 null인 문제 해결
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/engine/entity/EngineEntity.java
Labels: ✨ be, 🐛 fix

#161 [Fix] 트림 목록 조회 요청 형식 변경
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/trim/controller/TrimController.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/exception/BindingParamException.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/exception/GlobalExceptionHandler.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/trim/controller/TrimControllerTest.java
Labels: ✨ be, 🐛 fix

#160 [Feature] useFetch API custom hook 구현
  FE-MyCarMaster/.gitignore
  FE-MyCarMaster/src/components/Main/view/TrimContent.tsx
  FE-MyCarMaster/src/contexts/TrimContext.tsx
  FE-MyCarMaster/src/hooks/useFetch.ts
Labels: 🙇🏿‍♂️ fe, 🚀 feature

#163 [Design] 옵션박스 컴포넌트 디자인
  FE-MyCarMaster/src/components/Footer/view/DetailModelView/BodyTypeSelectView.tsx
  FE-MyCarMaster/src/components/Footer/view/DetailModelView/EngineSelectView.tsx
  FE-MyCarMaster/src/components/Footer/view/DetailModelView/WheelDriveSelectView.tsx
  FE-MyCarMaster/src/components/Footer/view/OptionSelect.tsx
  FE-MyCarMaster/src/components/common/NavigationList/NavigationItem.tsx
  FE-MyCarMaster/src/components/common/OptionBox/OptionBox.tsx
  FE-MyCarMaster/src/components/common/OptionBox/OptionBoxName.tsx
  FE-MyCarMaster/src/components/common/OptionBox/OptionBoxTopPrice.tsx
  FE-MyCarMaster/src/components/common/OptionBox/style.ts
  FE-MyCarMaster/src/contexts/OptionContext.tsx
  FE-MyCarMaster/src/contexts/QuotationContext.tsx
  FE-MyCarMaster/src/styles/GlobalStyle.ts
  FE-MyCarMaster/src/styles/Theme.ts
  FE-MyCarMaster/src/types/quotation.types.ts
Labels: 🙇🏿‍♂️ fe, 🎨 design

#162 [Fix] 엔진 목록 조회 요청 형식 query param으로 변경
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/engine/controller/EngineController.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/engine/controller/EngineControllerTest.java
Labels: ✨ be, 🐛 fix

#164 [Fix] 구동방식 목록 조회 요청 형식 query param으로 변경
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/wheeldrive/controller/WheelDriveController.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/wheeldrive/controller/WheelDriveControllerTest.java
Labels: ✨ be, 🐛 fix

#165 [Fix] 바디타입 목록 조회 요청 형식 query param으로 변경
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/body_type/controller/BodyTypeController.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/body_type/controller/BodyTypeControllerTest.java
Labels: ✨ be, 🐛 fix

#166 [Fix] 추가 옵션 목록 조회 요청 형식 query param으로 변경
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/controller/OptionController.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/option/controller/OptionControllerTest.java
Labels: ✨ be, 🐛 fix

#167 [Fix] 외장 목록 조회 요청 형식 query param으로 변경
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/color_exterior/controller/ExteriorColorController.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/color_exterior/controller/ExteriorColorControllerTest.java
Labels: ✨ be, 🐛 fix

#168 [Fix] 내장 목록 조회 요청 형식 query param으로 변경
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/color_interior/controller/InteriorColorController.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/color_interior/controller/InteriorColorControllerTest.java
Labels: ✨ be, 🐛 fix

#169 [Fix] 엔진에 따라 선택불가능해지는 옵션 목록 조회 요청 형식 query param으로 변경
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/engine/controller/EngineController.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/engine/dto/request/GetUnselectableOptionsByEngineRequest.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/engine/controller/EngineControllerTest.java
Labels: ✨ be, 🐛 fix

#170 [Release] 요청 형식 변경
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/body_type/controller/BodyTypeController.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/color_exterior/controller/ExteriorColorController.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/color_interior/controller/InteriorColorController.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/engine/controller/EngineController.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/engine/dto/request/GetUnselectableOptionsByEngineRequest.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/controller/OptionController.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/trim/controller/TrimController.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/wheeldrive/controller/WheelDriveController.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/exception/BindingParamException.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/exception/GlobalExceptionHandler.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/engine/entity/EngineEntity.java
  BE-MyCarMaster/src/main/resources/application-domain.yml
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/body_type/controller/BodyTypeControllerTest.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/color_exterior/controller/ExteriorColorControllerTest.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/color_interior/controller/InteriorColorControllerTest.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/engine/controller/EngineControllerTest.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/option/controller/OptionControllerTest.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/trim/controller/TrimControllerTest.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/wheeldrive/controller/WheelDriveControllerTest.java
Labels: ✨ be, 🔖 release

#172 [Docs] swagger request param 포맷 쿼리로 수정 및 테스트 에러 해결
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/body_type/controller/BodyTypeController.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/color_exterior/controller/ExteriorColorController.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/color_interior/controller/InteriorColorController.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/engine/controller/EngineController.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/controller/OptionController.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/trim/controller/TrimController.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/wheeldrive/controller/WheelDriveController.java
Labels: ✨ be, 📝 docs

#174 [Design] 홈 화면 레이아웃 구성
  FE-MyCarMaster/src/App.tsx
  FE-MyCarMaster/src/main.css
  FE-MyCarMaster/src/main.tsx
  FE-MyCarMaster/src/pages/Home.tsx
Labels: 🙇🏿‍♂️ fe, 🎨 design

#173 [Feature] 트림, 세부 모델, 색상 조회 API 연동
  FE-MyCarMaster/src/components/Footer/view/ColorView/ExteriorColorSelectView.tsx
  FE-MyCarMaster/src/components/Footer/view/DetailModelView/BodyTypeSelectView.tsx
  FE-MyCarMaster/src/components/Footer/view/DetailModelView/EngineSelectView.tsx
  FE-MyCarMaster/src/components/Footer/view/DetailModelView/WheelDriveSelectView.tsx
  FE-MyCarMaster/src/components/Footer/view/TrimSelect.tsx
  FE-MyCarMaster/src/components/Main/view/ColorView/ExteriorColorView.tsx
  FE-MyCarMaster/src/components/Main/view/DetailModelView/BodyTypeView.tsx
  FE-MyCarMaster/src/components/Main/view/DetailModelView/EngineView.tsx
  FE-MyCarMaster/src/components/Main/view/DetailModelView/WheelDriveView.tsx
  FE-MyCarMaster/src/components/Main/view/TrimContent.tsx
  FE-MyCarMaster/src/components/common/CategoryList/CategoryList.tsx
  FE-MyCarMaster/src/components/common/Graph/GraphList.tsx
  FE-MyCarMaster/src/contexts/CarPaintContext.tsx
  FE-MyCarMaster/src/contexts/DetailContext.tsx
  FE-MyCarMaster/src/contexts/ModelContext.tsx
  FE-MyCarMaster/src/contexts/OptionContext.tsx
  FE-MyCarMaster/src/contexts/TrimContext.tsx
Labels: 🙇🏿‍♂️ fe, 🚀 feature

#176 [Feature] 내장 색상 조회 api 연결
  FE-MyCarMaster/src/assets/images/2WD.png
  FE-MyCarMaster/src/assets/images/4WD.png
  FE-MyCarMaster/src/assets/images/BodyType_7.png
  FE-MyCarMaster/src/assets/images/BodyType_8.png
  FE-MyCarMaster/src/assets/images/Calligraphy.png
  FE-MyCarMaster/src/assets/images/Gasoline.png
  FE-MyCarMaster/src/assets/images/Prestige.png
  FE-MyCarMaster/src/assets/images/diesel.png
  FE-MyCarMaster/src/assets/images/exclusive.png
  FE-MyCarMaster/src/assets/images/leblanc.png
  FE-MyCarMaster/src/components/Footer/view/ColorView/ExteriorColorSelectView.tsx
  FE-MyCarMaster/src/components/Footer/view/ColorView/InteriorColorSelectView.tsx
  FE-MyCarMaster/src/components/Footer/view/DetailModelView/EngineSelectView.tsx
  FE-MyCarMaster/src/components/Footer/view/TrimSelect.tsx
  FE-MyCarMaster/src/components/Main/view/ColorView/ExteriorColorView.tsx
  FE-MyCarMaster/src/components/Main/view/ColorView/InteriorColorView.tsx
  FE-MyCarMaster/src/components/Main/view/DetailModelView/BodyTypeView.tsx
  FE-MyCarMaster/src/components/Main/view/DetailModelView/EngineView.tsx
  FE-MyCarMaster/src/components/Main/view/OptionContent.tsx
  FE-MyCarMaster/src/components/Main/view/TrimContent.tsx
  FE-MyCarMaster/src/components/common/Graph/GraphList.tsx
  FE-MyCarMaster/src/contexts/CarPaintContext.tsx
  FE-MyCarMaster/src/contexts/DetailContext.tsx
  FE-MyCarMaster/src/contexts/TrimContext.tsx
Labels: 🙇🏿‍♂️ fe, 🚀 feature

#107 [Setting] Vercel.json ignore 변수 추가
  FE-MyCarMaster/vercel.json
Labels: 🙇🏿‍♂️ fe, 🛠 setting

#185 [Setting] CORS 설정 수정
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/HealthController.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/config/cors/CorsConfig.java
Labels: ✨ be, 🛠 setting

#187 [Fix] checkStyle 수정
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/HealthController.java
Labels: ✨ be, 🐛 fix

#186 [Release] CORS 설정 수정
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/HealthController.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/body_type/controller/BodyTypeController.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/color_exterior/controller/ExteriorColorController.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/color_interior/controller/InteriorColorController.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/engine/controller/EngineController.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/controller/OptionController.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/trim/controller/TrimController.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/wheeldrive/controller/WheelDriveController.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/config/cors/CorsConfig.java
Labels: ✨ be, 🔖 release

#177 [Fix] 추가 옵션 목록 조회 로직 수정
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/dto/response/OptionDto.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/dto/response/SubOptionDto.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/domain/option/Option.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/option/adaptor/OptionJpaAdaptor.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/option/entity/OptionEntity.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/option/entity/TrimAdditionalOptionEntity.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/option/repository/TrimAdditionalOptionJpaRepository.java
  BE-MyCarMaster/src/main/resources/application-domain.yml
Labels: ✨ be, 🐛 fix

#188 [Fix] 전역 데이터 동작 에러 처리
  FE-MyCarMaster/src/components/Footer/view/ColorView/ExteriorColorSelectView.tsx
  FE-MyCarMaster/src/components/Footer/view/ColorView/InteriorColorSelectView.tsx
  FE-MyCarMaster/src/components/Footer/view/DetailModelView/BodyTypeSelectView.tsx
  FE-MyCarMaster/src/components/Footer/view/DetailModelView/EngineSelectView.tsx
  FE-MyCarMaster/src/components/Footer/view/DetailModelView/WheelDriveSelectView.tsx
  FE-MyCarMaster/src/components/Footer/view/TrimSelect.tsx
  FE-MyCarMaster/src/components/Main/view/ColorView/ExteriorColorView.tsx
  FE-MyCarMaster/src/components/Main/view/ColorView/InteriorColorView.tsx
  FE-MyCarMaster/src/components/Main/view/DetailModelView/BodyTypeView.tsx
  FE-MyCarMaster/src/components/Main/view/DetailModelView/EngineView.tsx
  FE-MyCarMaster/src/components/Main/view/DetailModelView/WheelDriveView.tsx
  FE-MyCarMaster/src/components/Main/view/TrimContent.tsx
  FE-MyCarMaster/src/components/common/ColorBox/OuterColorBox.tsx
  FE-MyCarMaster/src/components/common/Graph/GraphList.tsx
Labels: 🙇🏿‍♂️ fe, 🐛 fix

#182 [Feature] Engine UI
  iOS-MyCarMaster/MyCarMaster/MyCarMaster.xcodeproj/project.pbxproj
  iOS-MyCarMaster/MyCarMaster/MyCarMaster.xcodeproj/xcshareddata/xcschemes/Preview.xcscheme
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Engine/EngineView.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Engine/EngineViewController.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/General/BasicStepView.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/MainViewController.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Resources/Assets.xcassets/Engine/Contents.json
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Resources/Assets.xcassets/Engine/Diesel.imageset/Contents.json
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Resources/Assets.xcassets/Engine/Diesel.imageset/Diesel.png
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Resources/Assets.xcassets/Engine/Diesel.imageset/Diesel@2x.png
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Resources/Assets.xcassets/Engine/Diesel.imageset/Diesel@3x.png
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Resources/Assets.xcassets/Engine/gasoline.imageset/Contents.json
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Resources/Assets.xcassets/Engine/gasoline.imageset/gasoline.png
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Resources/Assets.xcassets/Engine/gasoline.imageset/gasoline@2x.png
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Resources/Assets.xcassets/Engine/gasoline.imageset/gasoline@3x.png
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Resources/Assets.xcassets/Trim/Calligraphy.imageset/Calligraphy.png
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Resources/Assets.xcassets/Trim/Calligraphy.imageset/Calligraphy@2x.png
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Resources/Assets.xcassets/Trim/Calligraphy.imageset/Calligraphy@3x.png
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Resources/Assets.xcassets/Trim/Calligraphy.imageset/Contents.json
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Resources/Assets.xcassets/Trim/Contents.json
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Resources/Assets.xcassets/Trim/Exclusive.imageset/Contents.json
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Resources/Assets.xcassets/Trim/Exclusive.imageset/Exclusive.png
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Resources/Assets.xcassets/Trim/Exclusive.imageset/Exclusive@2x.png
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Resources/Assets.xcassets/Trim/Exclusive.imageset/Exclusive@3x.png
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Resources/Assets.xcassets/Trim/LeBlanc.imageset/Contents.json
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Resources/Assets.xcassets/Trim/LeBlanc.imageset/LeBlanc.png
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Resources/Assets.xcassets/Trim/LeBlanc.imageset/LeBlanc@2x.png
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Resources/Assets.xcassets/Trim/LeBlanc.imageset/LeBlanc@3x.png
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Resources/Assets.xcassets/Trim/Prestige.imageset/Contents.json
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Resources/Assets.xcassets/Trim/Prestige.imageset/Prestige.png
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Resources/Assets.xcassets/Trim/Prestige.imageset/Prestige@2x.png
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Resources/Assets.xcassets/Trim/Prestige.imageset/Prestige@3x.png
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Trim/TrimView.swift
Labels: 🍎 ios, 🚀 feature, sprint[⼆]

#183 [Feature] WheelDrive UI
  iOS-MyCarMaster/MyCarMaster/MyCarMaster.xcodeproj/project.pbxproj
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Engine/EngineView.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/General/BasicListCell.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/General/EstimationView.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/General/StepNavigatorView.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/MainViewController.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Resources/Assets.xcassets/WheelDrive/2WD.imageset/2WD.png
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Resources/Assets.xcassets/WheelDrive/2WD.imageset/2WD@2x.png
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Resources/Assets.xcassets/WheelDrive/2WD.imageset/2WD@3x.png
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Resources/Assets.xcassets/WheelDrive/2WD.imageset/Contents.json
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Resources/Assets.xcassets/WheelDrive/4WD.imageset/4WD.png
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Resources/Assets.xcassets/WheelDrive/4WD.imageset/4WD@2x.png
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Resources/Assets.xcassets/WheelDrive/4WD.imageset/4WD@3x.png
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Resources/Assets.xcassets/WheelDrive/4WD.imageset/Contents.json
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Resources/Assets.xcassets/WheelDrive/Contents.json
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Trim/TrimView.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Util/UIView+Extension.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/WheelDrive/WheelDrive.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/WheelDrive/WheelDriveViewController.swift
Labels: 🍎 ios, 🚀 feature, sprint[⼆]

#184 [Feature] BodyType UI
  iOS-MyCarMaster/MyCarMaster/MyCarMaster.xcodeproj/project.pbxproj
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/General/BasicListCell.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/General/EstimationView.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/MainViewController.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Resources/Assets.xcassets/BodyType/BodyType_7.imageset/BodyType_7.png
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Resources/Assets.xcassets/BodyType/BodyType_7.imageset/BodyType_7@2x.png
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Resources/Assets.xcassets/BodyType/BodyType_7.imageset/BodyType_7@3x.png
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Resources/Assets.xcassets/BodyType/BodyType_7.imageset/Contents.json
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Resources/Assets.xcassets/BodyType/BodyType_8.imageset/BodyType_8.png
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Resources/Assets.xcassets/BodyType/BodyType_8.imageset/BodyType_8@2x.png
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Resources/Assets.xcassets/BodyType/BodyType_8.imageset/BodyType_8@3x.png
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Resources/Assets.xcassets/BodyType/BodyType_8.imageset/Contents.json
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Resources/Assets.xcassets/BodyType/Contents.json
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/BodyType/BodyTypeView.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/BodyType/BodyTypeViewController.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/Engine/EngineView.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/Engine/EngineViewController.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/Onboarding/OnboardingView.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/Onboarding/OnboardingViewController.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/Trim/TrimView.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/Trim/TrimViewController.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/WheelDrive/WheelDrive.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/WheelDrive/WheelDriveViewController.swift
Labels: 🍎 ios, 🚀 feature, sprint[⼆]

#195 [Feature] 차량 360도 회전 컴포넌트 구현
  FE-MyCarMaster/src/components/Main/view/ColorView/ExteriorColorView.tsx
  FE-MyCarMaster/src/components/common/CarRotation/CarRotation.tsx
Labels: 🙇🏿‍♂️ fe, 🚀 feature

#196 [Feature] Trim API 연동
  iOS-MyCarMaster/MCMNetwork/MCMNetwork/Resources/Dependency.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster.xcodeproj/project.pbxproj
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Model/DataTransferObject/Dummy/TrimDTODummy.json
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Model/DataTransferObject/RootDTO.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Model/DataTransferObject/TrimDTO.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Model/Entity/Trim.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/Trim/TrimView.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/Trim/TrimViewController.swift
Labels: 🍎 ios, 🚀 feature, sprint[⼆]

#197 [Feature] Engien API 연결
  iOS-MyCarMaster/MyCarMaster/MyCarMaster.xcodeproj/project.pbxproj
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Model/DataTransferObject/Dummy/EngineDTODummy.json
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Model/DataTransferObject/EngineDTO.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Model/DataTransferObject/RootDTO.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Model/Entity/Engine.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Resources/Assets.xcassets/Engine/gasoline.imageset/Gasoline.png
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Resources/Assets.xcassets/Engine/gasoline.imageset/Gasoline@2x.png
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/Engine/EngineView.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/Engine/EngineViewController.swift
Labels: 🍎 ios, 🚀 feature, sprint[⼆]

#200 [Feature] WheelDrive API 연동
  iOS-MyCarMaster/MVIFoundation/MVIFoundation.xcodeproj/xcshareddata/xcschemes/MVIFoundation.xcscheme
  iOS-MyCarMaster/MyCarMaster/MyCarMaster.xcodeproj/project.pbxproj
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Model/DataTransferObject/RootDTO.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Model/DataTransferObject/WheelDriveDTO.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Model/Entity/WheelDrive.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/WheelDrive/WheelDriveView.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/WheelDrive/WheelDriveViewController.swift
Labels: 🍎 ios, 🚀 feature, sprint[⼆]

#201 [Feature] BodyType API 연동
  iOS-MyCarMaster/MyCarMaster/MyCarMaster.xcodeproj/project.pbxproj
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Model/DataTransferObject/BodyTypeDTO.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Model/DataTransferObject/Dummy/BodyTypeDTO.json
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Model/DataTransferObject/Dummy/EngineDTO.json
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Model/DataTransferObject/Dummy/EngineDTODummy.json
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Model/DataTransferObject/Dummy/TrimDTO.json
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Model/DataTransferObject/Dummy/WheelDriveDTO.json
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Model/DataTransferObject/RootDTO.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Model/Entity/BodyType.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/BodyType/BodyTypeView.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/BodyType/BodyTypeViewController.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/Engine/EngineViewController.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/Trim/TrimViewController.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/WheelDrive/WheelDriveViewController.swift
Labels: 🍎 ios, 🚀 feature, sprint[⼆]

#193 [Fix] 엔진 변경에 따라 선택불가능해지는 옵션 목록 조회
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/engine/usecase/GetUnselectableOptionsByEngineUseCase.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/usecase/port/OptionPort.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/domain/option/Option.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/exception/InvalidOptionException.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/exception/MyCarMasterException.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/response/ResponseStatus.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/option/adaptor/OptionJpaAdaptor.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/option/entity/OptionEntity.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/option/entity/TrimAdditionalOptionEntity.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/option/repository/TrimAdditionalOptionJpaRepository.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/engine/usecase/GetUnselectableOptionsByEngineUseCaseTest.java
Labels: ✨ be, 🐛 fix

#199 [Design] 컴포넌트 Style 재정리
  FE-MyCarMaster/src/components/Footer/view/DetailModelView/BodyTypeSelectView.tsx
  FE-MyCarMaster/src/components/Footer/view/DetailModelView/EngineSelectView.tsx
  FE-MyCarMaster/src/components/Footer/view/DetailModelView/WheelDriveSelectView.tsx
  FE-MyCarMaster/src/components/Footer/view/OptionSelect.tsx
  FE-MyCarMaster/src/components/Footer/view/TrimSelect.tsx
  FE-MyCarMaster/src/components/Main/view/ColorView/ExteriorColorView.tsx
  FE-MyCarMaster/src/components/Main/view/ColorView/InteriorColorView.tsx
  FE-MyCarMaster/src/components/Main/view/DetailModelView/BodyTypeView.tsx
  FE-MyCarMaster/src/components/Main/view/DetailModelView/EngineView.tsx
  FE-MyCarMaster/src/components/Main/view/DetailModelView/WheelDriveView.tsx
  FE-MyCarMaster/src/components/Main/view/TrimContent.tsx
  FE-MyCarMaster/src/components/common/NavigationList/NavigationItem.tsx
  FE-MyCarMaster/src/components/common/OptionBox/OptionBox.tsx
  FE-MyCarMaster/src/components/common/OptionBox/OptionBoxButtonContainer.tsx
  FE-MyCarMaster/src/components/common/OptionBox/OptionBoxName.tsx
  FE-MyCarMaster/src/components/common/OptionBox/OptionBoxTopPrice.tsx
  FE-MyCarMaster/src/components/common/OptionBox/style.ts
  FE-MyCarMaster/src/contexts/CarPaintContext.tsx
  FE-MyCarMaster/src/contexts/DetailContext.tsx
  FE-MyCarMaster/src/contexts/ModelContext.tsx
  FE-MyCarMaster/src/contexts/QuotationContext.tsx
  FE-MyCarMaster/src/contexts/TrimContext.tsx
  FE-MyCarMaster/src/types/carpaint.types.ts
  FE-MyCarMaster/src/types/detail.types.ts
  FE-MyCarMaster/src/types/model.types.ts
  FE-MyCarMaster/src/types/options.types.ts
  FE-MyCarMaster/src/types/quotation.types.ts
  FE-MyCarMaster/src/types/trim.types.ts
Labels: 🙇🏿‍♂️ fe, 🎨 design

#202 [Feature] 옵션의 카테고리 타입 enum으로 변경
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/dto/response/OptionDto.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/dto/response/OptionEnum.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/domain/option/Category.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/domain/option/Option.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/option/entity/OptionEntity.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/engine/usecase/GetUnselectableOptionsByEngineUseCaseTest.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/option/usecase/GetOptionsUseCaseTest.java
Labels: ✨ be, 🚀 feature

#203 [Feature] 하단 확장에 사용되는 재사용 컴포넌트 생성
  FE-MyCarMaster/src/components/Footer/Footer.tsx
  FE-MyCarMaster/src/components/common/OptionBox/OptionBox.tsx
  FE-MyCarMaster/src/components/common/OptionBox/OptionBoxName.tsx
  FE-MyCarMaster/src/components/common/OptionBox/style.ts
  FE-MyCarMaster/src/components/common/SearchTrimBox/SearchTrimBox.tsx
  FE-MyCarMaster/src/components/common/SearchTrimBox/style.ts
  FE-MyCarMaster/src/components/common/TagItem/TagItem.tsx
  FE-MyCarMaster/src/components/common/TagItem/style.ts
  FE-MyCarMaster/src/styles/Theme.ts
Labels: 🙇🏿‍♂️ fe, 🎨 design

#211 [Feature] 하단 확장에 사용되는 재사용 컴포넌트 생성
  FE-MyCarMaster/src/App.tsx
  FE-MyCarMaster/src/components/Footer/FoldScreen.tsx
  FE-MyCarMaster/src/components/Footer/Footer.tsx
  FE-MyCarMaster/src/components/Footer/screen_view/ScreenContainer.tsx
  FE-MyCarMaster/src/components/common/CheckBox/OptionCheckBox.tsx
  FE-MyCarMaster/src/components/common/CheckBox/style.ts
  FE-MyCarMaster/src/components/common/SearchTrimBox/SearchTrimBox.tsx
  FE-MyCarMaster/src/components/common/SearchTrimBox/style.ts
  FE-MyCarMaster/src/components/common/TagItem/style.ts
  FE-MyCarMaster/src/styles/Theme.ts
Labels: 🙇🏿‍♂️ fe, 🚀 feature, 🎨 design

#212 [Feature] Step에 진입시 Preset이 설정됨
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/General/Cell/BasicListCell.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/General/Cell/ColorListCell.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/BodyType/BodyTypeViewController.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/Engine/EngineViewController.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/Exterior/ExteriorViewController.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/Trim/TrimViewController.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/WheelDrive/WheelDriveViewController.swift
Labels: 🍎 ios, 🚀 feature, 🐛 fix, sprint[⼆]

#213 [Feature] 최종 견적서 레이아웃 구성
  FE-MyCarMaster/src/App.tsx
  FE-MyCarMaster/src/assets/images/FindCarmasterTooltip.png
  FE-MyCarMaster/src/components/Footer/Footer.tsx
  FE-MyCarMaster/src/components/Footer/view/ColorView/ExteriorColorSelectView.tsx
  FE-MyCarMaster/src/components/Footer/view/ColorView/InteriorColorSelectView.tsx
  FE-MyCarMaster/src/components/Header/Header.tsx
  FE-MyCarMaster/src/components/Main/view/ColorView/ExteriorColorView.tsx
  FE-MyCarMaster/src/components/common/CarRotation/CarRotation.tsx
  FE-MyCarMaster/src/components/common/NavigationList/NavigationList.tsx
  FE-MyCarMaster/src/components/common/OptionBox/OptionBox.tsx
  FE-MyCarMaster/src/components/common/OptionBox/OptionBoxButtonContainer.tsx
  FE-MyCarMaster/src/components/common/QuotationList/QuotationItem.tsx
  FE-MyCarMaster/src/components/common/QuotationList/QuotationList.tsx
  FE-MyCarMaster/src/components/common/QuotationList/QuotationOptionItem.tsx
  FE-MyCarMaster/src/components/common/QuotationList/QuotationOptionList.tsx
  FE-MyCarMaster/src/contexts/QuotationContext.tsx
  FE-MyCarMaster/src/pages/Quotation.tsx
  FE-MyCarMaster/src/types/quotation.types.ts
Labels: 🙇🏿‍♂️ fe, 🚀 feature, sprint[⼆]

#205 [Feature] 기본 옵션 목록 조회
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/controller/OptionController.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/dto/request/GetDefaultOptionsRequest.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/dto/response/DefaultOptionDto.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/dto/response/GetDefaultOptionsResponse.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/usecase/GetDefaultOptionsUseCase.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/usecase/port/OptionPort.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/option/adaptor/OptionJpaAdaptor.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/option/entity/TrimDefaultOptionEntity.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/option/repository/TrimDefaultOptionJpaRepository.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/option/controller/OptionControllerTest.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/option/usecase/GetDefaultOptionsUseCaseTest.java
Labels: ✨ be, 🚀 feature

#219 [Fix]: lint 경고 수정
  FE-MyCarMaster/src/components/Footer/Footer.tsx
  FE-MyCarMaster/src/components/Main/view/ColorView/ExteriorColorView.tsx
  FE-MyCarMaster/src/components/common/CarRotation/CarRotation.tsx
  FE-MyCarMaster/src/components/common/CheckBox/style.ts
  FE-MyCarMaster/src/components/common/QuotationList/QuotationList.tsx
  FE-MyCarMaster/src/components/common/QuotationList/QuotationOptionItem.tsx
  FE-MyCarMaster/src/components/common/QuotationList/QuotationOptionList.tsx
Labels: 🙇🏿‍♂️ fe, 🐛 fix

#218 [Release] 프론트엔드 배포 테스트
  .github/workflows/fe-build.yml
  FE-MyCarMaster/src/App.tsx
  FE-MyCarMaster/src/assets/images/FindCarmasterTooltip.png
  FE-MyCarMaster/src/components/Footer/FoldScreen.tsx
  FE-MyCarMaster/src/components/Footer/Footer.tsx
  FE-MyCarMaster/src/components/Footer/screen_view/ScreenContainer.tsx
  FE-MyCarMaster/src/components/Footer/view/ColorView/ExteriorColorSelectView.tsx
  FE-MyCarMaster/src/components/Footer/view/ColorView/InteriorColorSelectView.tsx
  FE-MyCarMaster/src/components/Footer/view/DetailModelView/BodyTypeSelectView.tsx
  FE-MyCarMaster/src/components/Footer/view/DetailModelView/EngineSelectView.tsx
  FE-MyCarMaster/src/components/Footer/view/DetailModelView/WheelDriveSelectView.tsx
  FE-MyCarMaster/src/components/Footer/view/OptionSelect.tsx
  FE-MyCarMaster/src/components/Footer/view/TrimSelect.tsx
  FE-MyCarMaster/src/components/Header/Header.tsx
  FE-MyCarMaster/src/components/Main/view/ColorView/ExteriorColorView.tsx
  FE-MyCarMaster/src/components/Main/view/ColorView/InteriorColorView.tsx
  FE-MyCarMaster/src/components/Main/view/DetailModelView/BodyTypeView.tsx
  FE-MyCarMaster/src/components/Main/view/DetailModelView/EngineView.tsx
  FE-MyCarMaster/src/components/Main/view/DetailModelView/WheelDriveView.tsx
  FE-MyCarMaster/src/components/Main/view/TrimContent.tsx
  FE-MyCarMaster/src/components/common/CarRotation/CarRotation.tsx
  FE-MyCarMaster/src/components/common/CheckBox/OptionCheckBox.tsx
  FE-MyCarMaster/src/components/common/CheckBox/style.ts
  FE-MyCarMaster/src/components/common/ColorBox/OuterColorBox.tsx
  FE-MyCarMaster/src/components/common/Graph/GraphList.tsx
  FE-MyCarMaster/src/components/common/NavigationList/NavigationItem.tsx
  FE-MyCarMaster/src/components/common/NavigationList/NavigationList.tsx
  FE-MyCarMaster/src/components/common/OptionBox/OptionBox.tsx
  FE-MyCarMaster/src/components/common/OptionBox/OptionBoxButtonContainer.tsx
  FE-MyCarMaster/src/components/common/OptionBox/OptionBoxName.tsx
  FE-MyCarMaster/src/components/common/OptionBox/OptionBoxTopPrice.tsx
  FE-MyCarMaster/src/components/common/OptionBox/style.ts
  FE-MyCarMaster/src/components/common/QuotationList/QuotationItem.tsx
  FE-MyCarMaster/src/components/common/QuotationList/QuotationList.tsx
  FE-MyCarMaster/src/components/common/QuotationList/QuotationOptionItem.tsx
  FE-MyCarMaster/src/components/common/QuotationList/QuotationOptionList.tsx
  FE-MyCarMaster/src/components/common/SearchTrimBox/SearchTrimBox.tsx
  FE-MyCarMaster/src/components/common/SearchTrimBox/style.ts
  FE-MyCarMaster/src/components/common/TagItem/TagItem.tsx
  FE-MyCarMaster/src/components/common/TagItem/style.ts
  FE-MyCarMaster/src/contexts/CarPaintContext.tsx
  FE-MyCarMaster/src/contexts/DetailContext.tsx
  FE-MyCarMaster/src/contexts/ModelContext.tsx
  FE-MyCarMaster/src/contexts/QuotationContext.tsx
  FE-MyCarMaster/src/contexts/TrimContext.tsx
  FE-MyCarMaster/src/pages/Quotation.tsx
  FE-MyCarMaster/src/styles/Theme.ts
  FE-MyCarMaster/src/types/carpaint.types.ts
  FE-MyCarMaster/src/types/detail.types.ts
  FE-MyCarMaster/src/types/model.types.ts
  FE-MyCarMaster/src/types/options.types.ts
  FE-MyCarMaster/src/types/quotation.types.ts
  FE-MyCarMaster/src/types/trim.types.ts
Labels: 🙇🏿‍♂️ fe, 🔖 release

#220 [Release] 프론트엔드 배포 세팅 (최종)
  .github/workflows/fe-deploy.yml
Labels: 🙇🏿‍♂️ fe, 🔖 release

#221 [Chore] 색상 목록 조회 response에서 외장, 내장 색상 구분
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/color_exterior/dto/response/GetExteriorColorsResponse.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/color_interior/dto/response/GetInteriorColorsResponse.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/color_exterior/controller/ExteriorColorControllerTest.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/color_exterior/usecase/GetExteriorColorsUseCaseTest.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/color_interior/controller/InteriorColorControllerTest.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/color_interior/usecase/GetInteriorColorsUseCaseTest.java
Labels: ✨ be, 🍻 chore

#229 [Release] Pinpoint Collector ip 설정
  BE-MyCarMaster/config/pinpoint-agent/profiles/release/pinpoint.config
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/engine/exception/InvalidOptionException.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/engine/usecase/GetUnselectableOptionsByEngineUseCase.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/controller/EstimateController.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/dto/request/CreateEstimateRequest.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/dto/request/EstimateOptionDto.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/dto/response/CreateEstimateResponse.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/exception/InvalidEstimationException.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/usecase/CreateEstimateUseCase.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/usecase/port/EstimatePort.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/model/usecase/port/ModelPort.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/domain/body_type/BodyType.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/domain/color_exterior/ExteriorColor.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/domain/color_interior/InteriorColor.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/domain/engine/Engine.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/domain/model/Model.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/domain/trim/Trim.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/domain/wheel_dirve/WheelDrive.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/response/ResponseStatus.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/color_exterior/repository/ExteriorColorJpaRepository.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/color_interior/repository/InteriorColorJpaRepository.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/engine/repository/EngineJpaRepository.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/estimate/adaptor/EstimateJpaAdaptor.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/estimate/entity/EstimateAdditionalOptionEntity.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/estimate/entity/EstimateConsiderOptionEntity.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/estimate/entity/EstimateEntity.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/estimate/repository/EstimateJpaRepository.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/model/adaptor/ModelJpaAdaptor.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/option/repository/OptionJpaRepository.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/wheel_drive/repository/WheelDriveJpaRepository.java
  BE-MyCarMaster/src/main/resources/application-domain.yml
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/engine/usecase/GetUnselectableOptionsByEngineUseCaseTest.java
Labels: ✨ be, 🔖 release

#232 [Feature] 카마스터 상담 신청 Controller 구현
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/consult/controller/ConsultController.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/consult/dto/request/ApplyConsultingRequest.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/consult/dto/request/ClientDto.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/consult/usecase/ApplyConsultingUseCase.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/color_exterior/controller/ExteriorColorControllerTest.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/consult/ConsultControllerTest.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/trim/controller/TrimControllerTest.java
Labels: ✨ be, 🚀 feature

#231 [Feature] car master, store entity 구현
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/agency/entity/AgencyEntity.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/car_master/entity/CarMasterEntity.java
Labels: ✨ be, 🚀 feature

#233 [Setting] Pinpoint-agent 설정
  BE-MyCarMaster/Dockerfile
  BE-MyCarMaster/start-app.sh
Labels: ✨ be, 🛠 setting

#230 [Feature] trim_additional_optoin의 price를 option으로 이동
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/option/entity/OptionEntity.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/option/entity/TrimAdditionalOptionEntity.java
Labels: ✨ be, 🚀 feature

#224 [Feature] 견적서 완성 페이지 기능 구현
  FE-MyCarMaster/src/components/Footer/Footer.tsx
  FE-MyCarMaster/src/components/Footer/SelectListWrapper.tsx
  FE-MyCarMaster/src/components/Main/view/ColorView/ExteriorColorView.tsx
  FE-MyCarMaster/src/components/Main/view/ColorView/InteriorColorView.tsx
  FE-MyCarMaster/src/components/common/Button/TextButton.tsx
  FE-MyCarMaster/src/components/common/NavigationList/NavigationItem.tsx
  FE-MyCarMaster/src/components/common/QuotationList/QuotationItem.tsx
  FE-MyCarMaster/src/components/common/QuotationList/QuotationList.tsx
  FE-MyCarMaster/src/components/common/QuotationList/QuotationOptionItem.tsx
  FE-MyCarMaster/src/components/common/QuotationList/QuotationOptionList.tsx
  FE-MyCarMaster/src/components/common/SearchTrimBox/SearchTrimBox.tsx
  FE-MyCarMaster/src/contexts/QuotationContext.tsx
  FE-MyCarMaster/src/pages/Quotation.tsx
Labels: 🙇🏿‍♂️ fe, 🚀 feature

#235 [Refactor] 컴포넌트 Style 재정리
  FE-MyCarMaster/src/App.tsx
  FE-MyCarMaster/src/components/Footer/FoldScreen.tsx
  FE-MyCarMaster/src/components/Footer/Footer.tsx
  FE-MyCarMaster/src/components/Footer/SelectListWrapper.tsx
  FE-MyCarMaster/src/components/Footer/view/ColorSelect.tsx
  FE-MyCarMaster/src/components/Footer/view/DetailModelSelect.tsx
  FE-MyCarMaster/src/components/Footer/view/OptionSelect.tsx
  FE-MyCarMaster/src/components/Footer/view/TrimSelect.tsx
  FE-MyCarMaster/src/components/Header/Header.tsx
  FE-MyCarMaster/src/components/Main/MainView.tsx
  FE-MyCarMaster/src/components/Main/view/DetailModelView/BodyTypeView.tsx
  FE-MyCarMaster/src/components/Main/view/DetailModelView/WheelDriveView.tsx
  FE-MyCarMaster/src/components/Main/view/OptionContent.tsx
  FE-MyCarMaster/src/components/Main/view/TrimContent.tsx
  FE-MyCarMaster/src/components/common/CategoryList/CategoryItem.tsx
  FE-MyCarMaster/src/components/common/NavigationList/EstimatedPrice.tsx
  FE-MyCarMaster/src/components/common/NavigationList/NavigationItem.tsx
  FE-MyCarMaster/src/components/common/OptionBox/OptionBoxButtonContainer.tsx
  FE-MyCarMaster/src/components/common/OptionBox/style.ts
  FE-MyCarMaster/src/components/common/SearchTrimBox/style.ts
  FE-MyCarMaster/src/pages/Estimation.tsx
  FE-MyCarMaster/src/styles/Theme.ts
Labels: 🙇🏿‍♂️ fe, 🎨 design

#236 [Refactor] 컴포넌트 Style 재정리
  FE-MyCarMaster/src/components/Footer/Footer.tsx
  FE-MyCarMaster/src/components/Header/Header.tsx
  FE-MyCarMaster/src/components/Main/view/ColorView/InteriorColorView.tsx
  FE-MyCarMaster/src/components/Main/view/DetailModelView/BodyTypeView.tsx
  FE-MyCarMaster/src/components/Main/view/DetailModelView/WheelDriveView.tsx
  FE-MyCarMaster/src/components/common/ColorBox/InnerColorBox.tsx
  FE-MyCarMaster/src/components/common/ColorBox/OuterColorBox.tsx
  FE-MyCarMaster/src/components/common/ColorBox/style.ts
  FE-MyCarMaster/src/styles/Theme.ts
Labels: 🙇🏿‍♂️ fe, 🎨 design

#241 [Feature] 홈 화면 레이아웃 구성
  FE-MyCarMaster/src/App.tsx
  FE-MyCarMaster/src/components/Footer/FoldScreen.tsx
  FE-MyCarMaster/src/components/Footer/Footer.tsx
  FE-MyCarMaster/src/components/Header/Header.tsx
  FE-MyCarMaster/src/components/common/OptionBox/style.ts
  FE-MyCarMaster/src/pages/Home.tsx
Labels: 🙇🏿‍♂️ fe, 🚀 feature

#240 [Feature] 카마스터 상담 신청시 이메일 전송
  .github/workflows/be-release-cd.yml
  BE-MyCarMaster/.gitignore
  BE-MyCarMaster/Dockerfile
  BE-MyCarMaster/build.gradle
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/BeMyCarMasterApplication.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/consult/handler/MailSendEvent.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/consult/handler/MailSendHandler.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/consult/usecase/ApplyConsultingUseCase.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/config/CorsConfig.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/config/SwaggerConfig.java
  BE-MyCarMaster/src/main/resources/application-api.yml
  BE-MyCarMaster/src/main/resources/application-domain.yml
  BE-MyCarMaster/src/main/resources/templates/mail.html
Labels: ✨ be, 🚀 feature

#242 [Setting] gitignore 설정 추가
  BE-MyCarMaster/docker-compose.yml
  BE-MyCarMaster/src/main/resources/application-api.yml
Labels: ✨ be, 🛠 setting

#243 [Feature] agency entity에 gu 컬럼 및 representative option entity 추가
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/agency/entity/AgencyEntity.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/option/entity/RepresentativeOptionEntity.java
Labels: ✨ be, 🚀 feature

#244 [Setting] uuid와 별도로 pk 생성
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/dto/response/CreateEstimateResponse.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/usecase/CreateEstimateUseCase.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/domain/estimate/Estimate.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/estimate/adaptor/EstimateJpaAdaptor.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/estimate/entity/EstimateEntity.java
Labels: ✨ be, 🛠 setting

#246 [Feature] 하단 확장에 사용되는 재사용 컴포넌트 생성
  FE-MyCarMaster/src/components/Footer/view/TrimSelect.tsx
  FE-MyCarMaster/src/components/common/OptionBox/OptionBox.tsx
  FE-MyCarMaster/src/components/common/OptionList/OptionList.tsx
  FE-MyCarMaster/src/components/common/OptionList/style.ts
Labels: 🙇🏿‍♂️ fe, 🚀 feature, 🎨 design

#248 [Fix] 테이블 변경에 따른 구매 상담 신청 로직 수정
  .github/workflows/be-release-cd.yml
  BE-MyCarMaster/Dockerfile
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/consult/controller/ConsultController.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/consult/usecase/ApplyConsultingUseCase.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/controller/EstimateController.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/usecase/port/EstimatePort.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/config/CorsConfig.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/estimate/adaptor/EstimateJpaAdaptor.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/estimate/repository/EstimateJpaRepository.java
  BE-MyCarMaster/src/main/resources/application-domain.yml
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/consult/ConsultControllerTest.java
Labels: ✨ be, 🐛 fix

#249 [Setting] 프론트엔드 S3 배포 세팅
  .github/workflows/fe-deploy.yml
  FE-MyCarMaster/src/App.tsx
  FE-MyCarMaster/src/components/Footer/FoldScreen.tsx
  FE-MyCarMaster/src/components/Footer/Footer.tsx
  FE-MyCarMaster/src/components/Footer/SelectListWrapper.tsx
  FE-MyCarMaster/src/components/Footer/view/ColorSelect.tsx
  FE-MyCarMaster/src/components/Footer/view/DetailModelSelect.tsx
  FE-MyCarMaster/src/components/Footer/view/OptionSelect.tsx
  FE-MyCarMaster/src/components/Footer/view/TrimSelect.tsx
  FE-MyCarMaster/src/components/Header/Header.tsx
  FE-MyCarMaster/src/components/Main/MainView.tsx
  FE-MyCarMaster/src/components/Main/view/ColorView/ExteriorColorView.tsx
  FE-MyCarMaster/src/components/Main/view/ColorView/InteriorColorView.tsx
  FE-MyCarMaster/src/components/Main/view/DetailModelView/BodyTypeView.tsx
  FE-MyCarMaster/src/components/Main/view/DetailModelView/WheelDriveView.tsx
  FE-MyCarMaster/src/components/Main/view/OptionContent.tsx
  FE-MyCarMaster/src/components/Main/view/TrimContent.tsx
  FE-MyCarMaster/src/components/common/Button/TextButton.tsx
  FE-MyCarMaster/src/components/common/CategoryList/CategoryItem.tsx
  FE-MyCarMaster/src/components/common/ColorBox/InnerColorBox.tsx
  FE-MyCarMaster/src/components/common/ColorBox/OuterColorBox.tsx
  FE-MyCarMaster/src/components/common/ColorBox/style.ts
  FE-MyCarMaster/src/components/common/NavigationList/EstimatedPrice.tsx
  FE-MyCarMaster/src/components/common/NavigationList/NavigationItem.tsx
  FE-MyCarMaster/src/components/common/OptionBox/OptionBox.tsx
  FE-MyCarMaster/src/components/common/OptionBox/OptionBoxButtonContainer.tsx
  FE-MyCarMaster/src/components/common/OptionBox/style.ts
  FE-MyCarMaster/src/components/common/OptionList/OptionList.tsx
  FE-MyCarMaster/src/components/common/OptionList/style.ts
  FE-MyCarMaster/src/components/common/QuotationList/QuotationItem.tsx
  FE-MyCarMaster/src/components/common/QuotationList/QuotationList.tsx
  FE-MyCarMaster/src/components/common/QuotationList/QuotationOptionItem.tsx
  FE-MyCarMaster/src/components/common/QuotationList/QuotationOptionList.tsx
  FE-MyCarMaster/src/components/common/SearchTrimBox/SearchTrimBox.tsx
  FE-MyCarMaster/src/components/common/SearchTrimBox/style.ts
  FE-MyCarMaster/src/contexts/QuotationContext.tsx
  FE-MyCarMaster/src/pages/Estimation.tsx
  FE-MyCarMaster/src/pages/Home.tsx
  FE-MyCarMaster/src/pages/Quotation.tsx
  FE-MyCarMaster/src/styles/Theme.ts
Labels: 🙇🏿‍♂️ fe, 🛠 setting

#250 [Release] CORS 추가 설정
  .github/workflows/be-release-cd.yml
  BE-MyCarMaster/Dockerfile
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/consult/controller/ConsultController.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/consult/usecase/ApplyConsultingUseCase.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/controller/EstimateController.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/usecase/port/EstimatePort.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/config/CorsConfig.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/estimate/adaptor/EstimateJpaAdaptor.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/estimate/repository/EstimateJpaRepository.java
  BE-MyCarMaster/src/main/resources/application-domain.yml
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/consult/ConsultControllerTest.java
Labels: ✨ be, 🔖 release

#252 [Setting] allowMethods에 OPTIONS 메서드 추가
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/config/CorsConfig.java
Labels: ✨ be, 🛠 setting

#253 [Release] CORS 관련 설정
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/config/CorsConfig.java
Labels: ✨ be, 🔖 release

#254 [Setting] CORS 모든 origin 허용
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/config/CorsConfig.java
Labels: ✨ be, 🛠 setting

#255 [Release] 모든 origin 허용
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/config/CorsConfig.java
Labels: ✨ be

#251 [Feature] 카마스터 목록 조회 Controller 구현
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/car_master/controller/CarMasterController.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/car_master/dto/request/FilterEnum.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/car_master/dto/request/GetCarMasterRequest.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/car_master/dto/response/CarMasterDto.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/car_master/dto/response/GetCarMasterResponse.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/car_master/usecase/GetCarMasterUseCase.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/annotation/valid/EnumValidator.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/annotation/valid/ValidEnum.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/car_master/controller/CarMasterControllerTest.java
Labels: ✨ be, 🚀 feature

#258 [Feature] 하단 확장 레이아웃 및 컴포넌트 구성
  FE-MyCarMaster/src/assets/icons/SquareCheck.svg
  FE-MyCarMaster/src/components/Footer/FoldScreen.tsx
  FE-MyCarMaster/src/components/Footer/screen_view/MyTrimSearchScreen.tsx
  FE-MyCarMaster/src/components/Footer/screen_view/ScreenContainer.tsx
  FE-MyCarMaster/src/components/common/Button/Button.tsx
  FE-MyCarMaster/src/components/common/CheckBox/OptionCheckBox.tsx
  FE-MyCarMaster/src/components/common/CheckBox/style.ts
  FE-MyCarMaster/src/components/common/OptionList/OptionList.tsx
  FE-MyCarMaster/src/components/common/QuotationList/QuotationOptionItem.tsx
  FE-MyCarMaster/src/components/common/SearchTrimBox/SearchTrimBox.tsx
  FE-MyCarMaster/src/contexts/QuotationContext.tsx
  FE-MyCarMaster/src/types/quotation.types.ts
Labels: 🙇🏿‍♂️ fe, 🚀 feature

#256 [Feature] 모델별 대표옵션 목록 조회 구현
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/controller/OptionController.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/dto/request/GetRepresentativeOptionsRequest.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/dto/response/AppliedOptionDto.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/dto/response/FilterDto.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/dto/response/GetRepresentativeOptionsResponse.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/dto/response/RepresentativeOptionDto.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/usecase/GetRepresentativeOptionsUseCase.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/usecase/port/OptionPort.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/trim/usecase/port/TrimPort.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/option/adaptor/OptionJpaAdaptor.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/option/entity/OptionEntity.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/option/entity/RepresentativeOptionEntity.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/option/repository/RepresentativeOptionJpaRepository.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/option/repository/TrimAdditionalOptionJpaRepository.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/option/repository/TrimDefaultOptionJpaRepository.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/trim/adaptor/TrimJpaAdaptor.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/trim/repository/TrimJpaRepository.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/option/controller/OptionControllerTest.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/option/usecase/GetRepresentativeOptionsUseCaseTest.java
Labels: ✨ be, 🚀 feature

#257 [Feature] 카마스터 목록 조회 구현
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/car_master/controller/CarMasterController.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/car_master/dto/request/FilterEnum.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/car_master/dto/request/GetCarMasterRequest.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/car_master/dto/response/AgencyDto.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/car_master/dto/response/CarMasterAgencyDto.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/car_master/dto/response/CarMasterDto.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/car_master/dto/response/GetCarMasterResponse.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/car_master/usecase/GetCarMasterUseCase.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/car_master/usecase/port/AgencyPort.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/consult/usecase/port/CarMasterPort.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/domain/agency/Agency.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/domain/car_master/CarMaster.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/annotation/valid/EnumValidator.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/exception/GlobalExceptionHandler.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/agency/adaptor/AgencyJpaAdaptor.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/agency/entity/AgencyEntity.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/agency/repository/AgencyJpaRepository.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/car_master/adaptor/CarMasterJpaAdaptor.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/car_master/entity/CarMasterEntity.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/car_master/repository/CarMasterJpaRepository.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/car_master/controller/CarMasterControllerTest.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/car_master/usecase/GetCarMasterUseCaseTest.java
Labels: ✨ be, 🚀 feature

#259 [Feature] 대리점 목록 조회 Controller 구현
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/agency/controller/AgencyController.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/agency/dto/request/GetAgenciesRequest.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/agency/dto/response/AgencyDto.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/agency/dto/response/GetAgenciesResponse.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/agency/usecase/GetAgenciesUseCase.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/agency/AgencyControllerTest.java
Labels: ✨ be, 🚀 feature

#261 [Chore] 옵션 목록 조회시 카테고리 한글로 수정
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/dto/response/AppliedOptionDto.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/dto/response/DefaultOptionDto.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/option/dto/response/OptionDto.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/domain/option/Category.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/domain/option/Option.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/option/controller/OptionControllerTest.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/option/usecase/GetDefaultOptionsUseCaseTest.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/option/usecase/GetOptionsUseCaseTest.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/option/usecase/GetRepresentativeOptionsUseCaseTest.java
Labels: ✨ be, 🍻 chore

#262 [Feature] 지역구로 대리점 목록 조회 기능 구현
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/agency/controller/AgencyController.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/agency/dto/response/AgencyInGuDto.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/agency/dto/response/GetAgenciesResponse.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/agency/usecase/GetAgenciesUseCase.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/car_master/controller/CarMasterController.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/car_master/usecase/port/AgencyPort.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/agency/adaptor/AgencyJpaAdaptor.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/agency/entity/AgencyEntity.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/agency/repository/AgencyJpaRepository.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/agency/AgencyControllerTest.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/agency/usecase/GetAgenciesUseCaseTest.java
Labels: ✨ be, 🚀 feature

#260 [Feature] OptionView Basic 구현
  iOS-MyCarMaster/.gitignore
  iOS-MyCarMaster/MCMNetwork/.gitignore
  iOS-MyCarMaster/MCMNetwork/MCMNetwork.xcodeproj/project.pbxproj
  iOS-MyCarMaster/MCMNetwork/MCMNetwork/Resources/Dependency.swift
  iOS-MyCarMaster/MCMResource/MCMResource/Raw/Color.xcassets/Gold2.colorset/Contents.json
  iOS-MyCarMaster/MCMResource/MCMResource/Resource.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster.xcodeproj/project.pbxproj
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/General/BasicStepView.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/General/Cell/BasicListCell.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/General/Cell/ColorListCell.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/General/Cell/Protocol/Selectable.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/General/PaddingLabel.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/General/Protocol/ContentSizeEstimatable.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/General/Selectable/ButtonStyleSeletable.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/General/Selectable/CellStyleSelectable.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/General/Selectable/Selectable.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/General/Selectable/UIButton+Selectable.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/General/Selectable/UICollectionViewCell+Selectable.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Model/DataTransferObject/OptionDTO.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Model/Entity+/Option+.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Model/Entity/Option.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/BodyType/BodyTypeView.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/Engine/EngineView.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/Exterior/ExteriorView.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/Interior/InteriorView.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/Main/EstimationView.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/Main/MainViewController.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/Main/StepNavigatorView.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/Option/Cell/ButtonStyleCell.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/Option/Cell/OptionListCell.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/Option/Cell/OptionListCellMainState.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/Option/OptionView.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/Option/OptionViewController.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/Option/SubOptionButton.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/Trim/TrimView.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/WheelDrive/WheelDriveView.swift
Labels: 🍎 ios, 🚀 feature, sprint[三]

#264 [Feature] 하단 확장 레이아웃 및 컴포넌트 구성
  FE-MyCarMaster/src/components/Footer/FoldScreen.tsx
  FE-MyCarMaster/src/components/Footer/Footer.tsx
  FE-MyCarMaster/src/components/Footer/screen_view/DefaultOptionScreen.tsx
  FE-MyCarMaster/src/components/Footer/screen_view/MyTrimSearchScreen.tsx
  FE-MyCarMaster/src/components/Main/view/ColorContent.tsx
  FE-MyCarMaster/src/components/Main/view/DetailModelContent.tsx
  FE-MyCarMaster/src/components/Main/view/OptionContent.tsx
  FE-MyCarMaster/src/components/common/CategoryList/CategoryList.tsx
  FE-MyCarMaster/src/components/common/OptionList/GridOptionList.tsx
  FE-MyCarMaster/src/components/common/OptionList/OptionList.tsx
  FE-MyCarMaster/src/components/common/OptionList/style.ts
Labels: 🙇🏿‍♂️ fe, 🚀 feature, 🎨 design

#265 [Setting] swagger server Url 설정
  .github/workflows/be-release-cd.yml
  BE-MyCarMaster/Dockerfile
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/config/SwaggerConfig.java
  BE-MyCarMaster/src/main/resources/application-api.yml
Labels: ✨ be, 🛠 setting

#268 [Feature] 재사용 모달 구현
  FE-MyCarMaster/index.html
  FE-MyCarMaster/src/components/Footer/Footer.tsx
  FE-MyCarMaster/src/components/Footer/view/DetailModelView/EngineSelectView.tsx
  FE-MyCarMaster/src/components/Footer/view/TrimSelect.tsx
  FE-MyCarMaster/src/components/Header/Header.tsx
  FE-MyCarMaster/src/components/common/CarRotation/CarRotation.tsx
  FE-MyCarMaster/src/components/common/Modals/ModalContents/ChangeEngineModal.tsx
  FE-MyCarMaster/src/components/common/Modals/ModalContents/ChangeTrimModal.tsx
  FE-MyCarMaster/src/components/common/Modals/ModalContents/ExitModal.tsx
  FE-MyCarMaster/src/components/common/Modals/Modals.tsx
  FE-MyCarMaster/src/components/common/OptionDescription/OptionDescription.tsx
  FE-MyCarMaster/src/components/common/QuotationList/QuotationItem.tsx
  FE-MyCarMaster/src/components/common/QuotationList/QuotationList.tsx
  FE-MyCarMaster/src/components/common/QuotationList/QuotationOptionItem.tsx
  FE-MyCarMaster/src/components/common/QuotationList/QuotationOptionList.tsx
  FE-MyCarMaster/src/constants/Modal.constants.ts
  FE-MyCarMaster/src/contexts/QuotationContext.tsx
  FE-MyCarMaster/src/pages/Quotation.tsx
  FE-MyCarMaster/src/types/options.types.ts
  FE-MyCarMaster/src/types/quotation.types.ts
Labels: 🙇🏿‍♂️ fe, 🚀 feature

#271 [Feature]추가 옵션 뷰 구성
  FE-MyCarMaster/src/components/Footer/screen_view/MyTrimSearchScreen.tsx
  FE-MyCarMaster/src/components/Footer/view/ColorView/ExteriorColorSelectView.tsx
  FE-MyCarMaster/src/components/Footer/view/ColorView/InteriorColorSelectView.tsx
  FE-MyCarMaster/src/components/Footer/view/DetailModelView/BodyTypeSelectView.tsx
  FE-MyCarMaster/src/components/Footer/view/DetailModelView/EngineSelectView.tsx
  FE-MyCarMaster/src/components/Footer/view/DetailModelView/WheelDriveSelectView.tsx
  FE-MyCarMaster/src/components/Footer/view/OptionSelect.tsx
  FE-MyCarMaster/src/components/Footer/view/TrimSelect.tsx
  FE-MyCarMaster/src/components/Main/view/ColorView/ExteriorColorView.tsx
  FE-MyCarMaster/src/components/Main/view/ColorView/InteriorColorView.tsx
  FE-MyCarMaster/src/components/Main/view/DetailModelView/BodyTypeView.tsx
  FE-MyCarMaster/src/components/Main/view/DetailModelView/EngineView.tsx
  FE-MyCarMaster/src/components/Main/view/DetailModelView/WheelDriveView.tsx
  FE-MyCarMaster/src/components/Main/view/OptionContent.tsx
  FE-MyCarMaster/src/components/Main/view/TrimContent.tsx
  FE-MyCarMaster/src/components/common/NavigationList/NavigationItem.tsx
  FE-MyCarMaster/src/components/common/OptionDescription/OptionDescription.tsx
  FE-MyCarMaster/src/constants/Option.constants.ts
  FE-MyCarMaster/src/contexts/OptionContext.tsx
Labels: 🙇🏿‍♂️ fe, 🚀 feature

#269 [Feature] 트림의 모든 기본 옵션 목록 조회 기능 구현
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/trim/dto/response/GetTrimDefaultOptionsResponse.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/trim/dto/response/TrimDefaultOptionDto.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/trim/usecase/GetTrimDefaultOptionsUseCase.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/trim/controller/TrimControllerTest.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/trim/usecase/GetTrimDefaultOptionsUseCaseTest.java
Labels: ✨ be, 🚀 feature

#274 [Feature] 기본 옵션 모달 및 옵션 상세 보기 모달 구현
  FE-MyCarMaster/src/components/Footer/screen_view/MyTrimSearchScreen.tsx
  FE-MyCarMaster/src/components/Footer/view/TrimSelect.tsx
  FE-MyCarMaster/src/components/common/BasicOptionModal/BasicOptionModal.tsx
  FE-MyCarMaster/src/components/common/CheckBox/OptionCheckBox.tsx
  FE-MyCarMaster/src/components/common/OptionBox/OptionBox.tsx
  FE-MyCarMaster/src/components/common/OptionDescriptionModal/OptionDescriptionModal.tsx
  FE-MyCarMaster/src/components/common/OptionList/style.ts
  FE-MyCarMaster/src/contexts/QuotationContext.tsx
  FE-MyCarMaster/src/types/options.types.ts
  FE-MyCarMaster/src/types/quotation.types.ts
Labels: 🙇🏿‍♂️ fe, 🚀 feature

#276 [Fix] 스타일 및 내게 맞는 트림 찾기 옵션 적용
  FE-MyCarMaster/src/components/Footer/view/OptionSelect.tsx
  FE-MyCarMaster/src/components/Header/Header.tsx
  FE-MyCarMaster/src/contexts/OptionContext.tsx
  FE-MyCarMaster/src/pages/Quotation.tsx
  FE-MyCarMaster/src/types/options.types.ts
Labels: 🙇🏿‍♂️ fe, 🎨 design, 🐛 fix

#277 [Release] v0.2배포(api 일부 미연동)
  FE-MyCarMaster/src/components/Footer/view/OptionSelect.tsx
  FE-MyCarMaster/src/components/Header/Header.tsx
  FE-MyCarMaster/src/contexts/OptionContext.tsx
  FE-MyCarMaster/src/pages/Quotation.tsx
  FE-MyCarMaster/src/types/options.types.ts
Labels: 🙇🏿‍♂️ fe, 🔖 release

#270 [Feature] 카마스터 정보에 소속 대리점 추가
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/agency/dto/response/CarMasterInAgencyDto.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/car_master/entity/CarMasterEntity.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/agency/usecase/GetCarMastersInAgencyUseCaseTest.java
Labels: ✨ be, 🚀 feature

#286 [Feature] 견적서 조회 기능 구현
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/controller/EstimateController.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/dto/response/GetEstimateResponse.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/dto/response/SimpleBodyTypeDto.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/dto/response/SimpleEngineDto.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/dto/response/SimpleExteriorColorDto.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/dto/response/SimpleInteriorColorDto.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/dto/response/SimpleOptionDto.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/dto/response/SimpleTrimDto.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/dto/response/SimpleWheelDriveDto.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/usecase/GetEstimateUseCase.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/usecase/port/EstimatePort.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/domain/estimate/Estimate.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/color_exterior/entity/ExteriorColorEntity.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/color_exterior/entity/TrimExteriorColorEntity.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/color_interior/entity/InteriorColorEntity.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/color_interior/entity/TrimInteriorColorEntity.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/estimate/adaptor/EstimateJpaAdaptor.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/estimate/entity/EstimateAdditionalOptionEntity.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/estimate/entity/EstimateConsiderOptionEntity.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/estimate/entity/EstimateEntity.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/estimate/repository/EstimateJpaRepository.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/option/entity/OptionEntity.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/trim/entity/TrimEntity.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/estimate/controller/EstimateControllerTest.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/estimate/usecase/GetEstimateUseCaseTest.java
Labels: ✨ be, 🚀 feature

#287 [Setting] Redis 설정
  .github/workflows/be-release-cd.yml
  BE-MyCarMaster/Dockerfile
  BE-MyCarMaster/build.gradle
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/config/CacheConfig.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/config/RedisConfig.java
  BE-MyCarMaster/src/main/resources/application-domain.yml
Labels: ✨ be, 🛠 setting

#288 [Release] Redis 연결
  .github/workflows/be-release-cd.yml
  BE-MyCarMaster/Dockerfile
  BE-MyCarMaster/build.gradle
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/agency/dto/response/CarMasterInAgencyDto.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/controller/EstimateController.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/dto/response/GetEstimateResponse.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/dto/response/SimpleBodyTypeDto.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/dto/response/SimpleEngineDto.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/dto/response/SimpleExteriorColorDto.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/dto/response/SimpleInteriorColorDto.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/dto/response/SimpleOptionDto.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/dto/response/SimpleTrimDto.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/dto/response/SimpleWheelDriveDto.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/usecase/GetEstimateUseCase.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/estimate/usecase/port/EstimatePort.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/trim/dto/response/GetTrimDefaultOptionsResponse.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/trim/dto/response/TrimDefaultOptionDto.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/api/trim/usecase/GetTrimDefaultOptionsUseCase.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/domain/estimate/Estimate.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/config/CacheConfig.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/config/RedisConfig.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/car_master/entity/CarMasterEntity.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/color_exterior/entity/ExteriorColorEntity.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/color_exterior/entity/TrimExteriorColorEntity.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/color_interior/entity/InteriorColorEntity.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/color_interior/entity/TrimInteriorColorEntity.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/estimate/adaptor/EstimateJpaAdaptor.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/estimate/entity/EstimateAdditionalOptionEntity.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/estimate/entity/EstimateConsiderOptionEntity.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/estimate/entity/EstimateEntity.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/estimate/repository/EstimateJpaRepository.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/option/entity/OptionEntity.java
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/infrastructure/jpa/trim/entity/TrimEntity.java
  BE-MyCarMaster/src/main/resources/application-domain.yml
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/agency/usecase/GetCarMastersInAgencyUseCaseTest.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/estimate/controller/EstimateControllerTest.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/estimate/usecase/GetEstimateUseCaseTest.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/trim/controller/TrimControllerTest.java
  BE-MyCarMaster/src/test/java/softeer/be_my_car_master/api/trim/usecase/GetTrimDefaultOptionsUseCaseTest.java
Labels: ✨ be, 🔖 release

#289 [Fix] 환경변수 설정 수정
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/config/RedisConfig.java
  BE-MyCarMaster/src/main/resources/application-domain.yml
Labels: ✨ be, 🐛 fix

#290 [Release] 환경변수 설정 수정
  BE-MyCarMaster/src/main/java/softeer/be_my_car_master/global/config/RedisConfig.java
  BE-MyCarMaster/src/main/resources/application-domain.yml
Labels: ✨ be, 🔖 release

#273 [Feature] Option API 연동
  iOS-MyCarMaster/MCMNetwork/MCMNetwork.xcodeproj/project.pbxproj
  iOS-MyCarMaster/MyCarMaster/MyCarMaster.xcodeproj/project.pbxproj
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Model/DataTransferObject/Dummy/OptionDTO.json
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Model/DataTransferObject/OptionDTO.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Model/DataTransferObject/RootDTO.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Model/Entity+/Option+.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Model/Entity/Option.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/BodyType/BodyTypeViewController.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/Engine/EngineViewController.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/Exterior/ExteriorViewController.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/Interior/InteriorViewController.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/Option/Cell/OptionListCell.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/Option/Cell/OptionListCellMainState.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/Option/DetailOptionModalView.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/Option/OptionView.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/Option/OptionViewController.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/Option/SubOptionButton.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/Trim/TrimViewController.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMaster/Sceen/WheelDrive/WheelDriveViewController.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMasterTests/DecodeDTO/DecodeOptionDTOTests.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMasterTests/DecodeDTO/DecodeTrimDTOTests.swift
  iOS-MyCarMaster/MyCarMaster/MyCarMasterTests/DecodeDTO/FetchFromBundle.swift
Labels: 🍎 ios, 🚀 feature, sprint[三]
